PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX oms_latest_new: <http://cambridgesemantics.com/DataSource/cbd5ec538476e3efb7264e3825565c2a/>
PREFIX public: <http://cambridgesemantics.com/DataSource/cbd5ec538476e3efb7264e3825565c2a/OMS_Latest_New/public/>
PREFIX s: <http://cambridgesemantics.com/ontologies/DataToolkit#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ont: <http://cambridgesemantics.com/Layer/1f3cbffb3f734b0193ab88e3f0e55c81/Model#>
 
INSERT { 
    GRAPH ${targetGraph} { 
        ?start_node_obj ?relationship_class ?end_node_obj .
        ?relationship_obj a ?relationship_class ;
          rdfs:label ?relationship_name ;
          rdfs:id ?relationship_id ;
          .
         # below section is what makesAServer display "Relationship" in its model 
         # under "Explore" for this Graphmart
        ?relationship_obj a ont:Relationship ;
          ont:Relationship.id ?relationship_id ;
          ont:Relationship.acm_string ?acm_string ;
          ont:Relationship.Tags ?tags ;
          ont:Relationship.labels ?labels ;
          ont:Relationship.confidence ?confidence ;     
          ont:Relationship.start_node_id ?start_node_id ;  
          ont:Relationship.end_node_id ?end_node_id ;  
          ont:Relationship.object_property_iri ?object_property_iri ; 
          ont:Relationship.object_property_name ?object_property_name ;
          ont:Relationship.source_id ?source_id ;
          ont:Relationship.relationship_name ?relationship_name;
      .
  }
}
WHERE {
    SERVICE <http://cambridgesemantics.com/services/DataToolkit> {
        ?generator a s:RdfGenerator, s:OntologyGenerator ;
            s:as (?subject ?predicate ?object) ;
            s:base ${targetGraph} ;
            .
        oms_latest_new:OMS_Latest_New a s:DbSource ;
            s:url "{{@db.cbd5ec538476e3efb7264e3825565c2a.url}}" ;
            s:username "{{@db.cbd5ec538476e3efb7264e3825565c2a.user}}" ;
            s:password "{{@db.cbd5ec538476e3efb7264e3825565c2a.password}}" ;
            s:database "{{@db.cbd5ec538476e3efb7264e3825565c2a.database}}" ;
            .
        public:node a s:DbSource ;
            s:using oms_latest_new:OMS_Latest_New ;
            s:table "public.relationship" ;
            s:model "relationship" ;
            s:query "select r.id as relationship_id, r.start_node_id as start_node_id, r.object_property_iri as object_property_iri, r.end_node_id as end_node_id, r.tags as tags, r.labels as labels, r.name as relationship_name, r.confidence as confidence, r.object_property_name as object_property_name, r.source_id as source_id from public.relationship r LEFT JOIN public.acm_container a ON r.acm_id = a.id" ;
                ?relationship_id (xsd:string) ;
                ?start_node_id (xsd:string) ;
                ?object_property_iri (xsd:string) ;
                ?end_node_id (xsd:string) ;
                ?acm_string (xsd:string) ;
                ?tags (xsd:list) ;
                ?labels (xsd:list) ;
                ?relationship_name (xsd:string) ;
                ?confidence (xsd:string) ;
                ?object_property_name (xsd:string) ;
                ?source_id (xsd:string) ;
                 .
            BIND(IRI("http://cambridgesemantics.com/Layer/1f3cbffb3f734b0193ab88e3f0e55c81/{{?start_node_id}}") AS ?start_node_obj)
            BIND(IRI("http://cambridgesemantics.com/Layer/1f3cbffb3f734b0193ab88e3f0e55c81/{{?end_node_id}}") AS ?end_node_obj)
            BIND(IRI("{{?object_property_iri}}") AS ?relationship_class)
            BIND(IRI("http://cambridgesemantics.com/Layer/1f3cbffb3f734b0193ab88e3f0e55c81/{{?relationship_id}}") AS ?relationship_obj)
    
    }
}
