PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX oms_latest_new: <http://cambridgesemantics.com/DataSource/cbd5ec538476e3efb7264e3825565c2a/>
PREFIX public: <http://cambridgesemantics.com/DataSource/cbd5ec538476e3efb7264e3825565c2a/OMS_Latest_New/public/>
PREFIX s: <http://cambridgesemantics.com/ontologies/DataToolkit#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ont: <http://cambridgesemantics.com/Layer/1f3cbffb3f734b0193ab88e3f0e55c81/Model#>

INSERT { 
	GRAPH ${targetGraph} { 
        ?node_obj a ont:Node ;
        ont:Node.id ?node_id ;
        ont:Node.allegiance ?allegiance ;
        ont:Node.allegiance_aor ?allegiance_aor ;
        ont:Node.acm_string ?acm_string ;
        ont:Node.labels ?labels ;
        ont:Node.tags ?tags ;
        ont:Node.class_iri ?class_iri ;
        ont:Node.class_name ?class_name ;
        ont:Node.tier ?tier ;
        ont:Node.guide_id ?guide_id ;
        ont:Node.is_nso ?is_nso ;
        ont:Node.current_aor ?current_aor ;
        ont:Node.ifc_codes ?ifc_codes ;
        ont:Node.symbol_id_code ?symbol_id_code ;
        ont:Node.class_iri_chain ?class_iri_chain ;
        ont:Node.name ?name  .
  }
}
WHERE {
	SERVICE <http://cambridgesemantics.com/services/DataToolkit> {
		?generator a s:RdfGenerator, s:OntologyGenerator ;
			s:as (?subject ?predicate ?object) ;
			s:base ${targetGraph} ;
			.
		oms_latest_new:OMS_Latest_New a s:DbSource ;
			s:url "{{@db.cbd5ec538476e3efb7264e3825565c2a.url}}" ;
			s:username "{{@db.cbd5ec538476e3efb7264e3825565c2a.user}}" ;
			s:password "{{@db.cbd5ec538476e3efb7264e3825565c2a.password}}" ;
			s:database "{{@db.cbd5ec538476e3efb7264e3825565c2a.database}}" ;
			.
		public:node a s:DbSource ;
			s:using oms_latest_new:OMS_Latest_New ;
			s:table "public.node" ;
			s:model "node" ;
            s:query "select n.id as node_id, n.allegiance as allegiance, n.allegiance_aor as allegiance_aor, n.class_iri as class_iri, n.class_name as class_name, a.acm_string as acm_string, n.labels as labels, n.tags as tags, n.tier as tier, n.guide_id as guide_id, n.is_nso as is_nso, n.current_aor as current_aor, n.ifc_codes as ifc_codes, n.symbol_id_code as symbol_id_code, n.class_iri_chain as class_iri_chain, n.name as name from public.node n left join public.acm_container a on n.acm_id = a.id";
            ?node_id (xsd:string);
            ?allegiance (xsd:string);
            ?allegiance_aor (xsd:string);
            ?class_iri (xsd:string);
            ?class_name (xsd:string);
            ?acm_string (xsd:string);
            ?labels (xsd:list);
            ?tags (xsd:list);
            ?tier (xsd:string);
            ?guide_id (xsd:string);
            ?is_nso (xsd:boolean);
            ?current_aor (xsd:string);
            ?ifc_codes (xsd:list);
            ?symbol_id_code (xsd:string);
            ?class_iri_chain (xsd:list);
            ?name (xsd:string);
            .  
            BIND(IRI("http://cambridgesemantics.com/Layer/1f3cbffb3f734b0193ab88e3f0e55c81/{{?node_id}}") AS ?node_obj)
	}
}
