services:
  oms_sensemaking:
    build:
      context: .
      dockerfile: dockerfiles/dev/Dockerfile
      secrets:
        - mynetrc
      args:
        PIP_EXTRA_INDEX_URL: ${PIP_INDEX}
    ports:
      - 5001:${UVICORN_PORT:-8443}
    environment:
      # database config
      DB_HOST: postgis
      DB_USER: ${DB_USER:-${PGUSER:-appuser}}
      DB_PASSWORD: ${DB_PASSWORD:-${PGPASSWORD}}
      DB_SSL: ${DB_SSL:-true}
      PGHOST: postgis
      UVICORN_PORT: ${UVICORN_PORT:-8443}
      UVICORN_SSL_KEYFILE: ${UVICORN_SSL_KEYFILE}
      UVICORN_SSL_CERTFILE: ${UVICORN_SSL_CERTFILE}
      UVICORN_SSL_CERT_REQS: ${UVICORN_SSL_CERT_REQS:-0}  # set this to 1 to request client certs
      UVICORN_LOG_LEVEL: ${UVICORN_LOG_LEVEL:-info}

      # misc.
      APP_LOG_LEVEL: ${APP_LOG_LEVEL:-INFO}
      RELOAD_APP: ${RELOAD_APP:-1}
    volumes:
      - .:/app
      - ./etc/pki:/opt/common/pki
    healthcheck:
      test: ["CMD-SHELL", "/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    depends_on:
      - postgis

  postgis:
    image: postgis/postgis:16-3.4-alpine
    platform: linux/amd64  # see https://github.com/postgis/docker-postgis/issues/216
    ports:
      - "${POSTGRES_PORT:-}:5432"
    environment:
      # Admin user
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      # Application user
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      # Database names
      DB_NAME: ${DB_NAME}
      DB_NAME_OMSB: ${DB_NAME_OMSB}
      DB_TEMPLATE: ${DB_TEMPLATE}

      # SSL certs
      UVICORN_SSL_KEYFILE: ${UVICORN_SSL_KEYFILE}
      UVICORN_SSL_CERTFILE: ${UVICORN_SSL_CERTFILE}
    volumes:
      - postgis:/var/lib/postgresql/data
      - ./etc/pki:/opt/common/pki:rw
      - ./docker/postgis/initdb.d/20_oms-sensemaking.sh:/docker-entrypoint-initdb.d/20_oms-sensemaking.sh
      - ./docker/postgis/initdb.d/30_enable-ssl.sh:/docker-entrypoint-initdb.d/30_enable-ssl.sh
      - ./docker/postgis/initdb.d/40_enable-hstore.sh:/docker-entrypoint-initdb.d/40_enable-hstore.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    profiles:
      - dev
    image: dpage/pgadmin4:8
    volumes:
      - ./docker/postgis/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-dev@blackcape.io}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-$POSTGRES_PASSWORD}
      PGADMIN_CONFIG_LOGIN_BANNER: "${PGADMIN_CONFIG_LOGIN_BANNER:-'<h4>Development Database</h4>'}"
    ports:
      - 5050:80
    depends_on:
      - postgis

  omsb-init:
    image: ${DOCKER_REGISTRY}/aio4/dev/services/oms/oms-bridge:${OMSB_VERSION}
    container_name: omsb-init
    env_file:
      - ./docker/omsb/omsb.env
    environment:
      OMSB_SERVICE: init
      OMSB_ENABLE_LIQUIDBASE: true
      POSTGRES_PASSWORD:
    volumes:
      - ./etc/pki:/opt/oms-bridge/pki
    depends_on:
      postgis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      aac2:
        condition: service_started
    profiles:
      - local

  # NOTE: The omsb container should not require the "guide" service,
  #       but it may try to resolve the hostnames, which results in a stack
  #       trace being logged. This can be ignored, since the purpose of this
  #       configuration is to provide a minimal omsb for development & testing.
  omsb2:
    image: ${DOCKER_REGISTRY}/aio4/dev/services/oms/oms-bridge:${OMSB_VERSION}
    environment:
      # PostgreSQL/PostGIS variables
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD:
      OMSB_SERVICE: api
    env_file:
      - ./docker/omsb/omsb.env
    volumes:
      - ./etc/pki:/opt/oms-bridge/pki
      - ./etc/whitelist.txt:/opt/oms-bridge/etc/config/external/Whitelist.txt
      - ./docker/omsb/LocalCollectionStatusThresholds.yaml:/opt/oms-bridge/etc/collectionstatus/CollectionStatusThresholds.yaml
      - ./docker/omsb/SystemLabels.yaml:/opt/oms-bridge/etc/config/external/SystemLabels.yaml
    ports:
      - "8010:8000"
      - "8020:8443"
    depends_on:
      postgis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      omsb-init:
        condition: service_started
    profiles:
      - local

  localstack:
    hostname: localstack
    image: localstack/localstack:3.4.0
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - OMSB_SQS_QUEUE_CONFIG=geoSensemakerTrigger,inferenceSensemakerTrigger,resolutionTrigger,milSymbolTrigger
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./docker/localstack:/etc/localstack/init/ready.d"
    profiles:
      - local

  aac2:
#    hostname: aac2
#    container_name: aac2
    image: ${DOCKER_REGISTRY}/dpaas-internal/aac/ent-aac-service:2.1.15.3
    command: sh -c "./entrypoint.sh"
    volumes:
      - ./etc/pki:/opt/common/pki
      - ./docker/aac2/entrypoint.sh:/app/entrypoint.sh
      - ./docker/aac2/users:/app/users
    ports:
      - "5022:3000"
    environment:
      HOST_URL: 0.0.0.0:3000
      DEVELOPMENT_MODE: "true"
      ENABLE_L1_CACHE_SYNC: "false"
      HOST_TLS_CERT_FILE: /opt/common/pki/server.public
      HOST_TLS_KEY_FILE: /opt/common/pki/server.private
      TEMPLATES_PARSE_INTERVAL: 15s
    profiles:
      - local

  doccano:
    image: doccano/doccano
    ports:
      - "8000:8000"
    environment:
      ADMIN_USERNAME: admin
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: password
    volumes:
     - doccano-db:/data
    profiles:
      - local

#  corenlp:
#    command: docker buildx build -t corenlp https://github.com/NLPbox/stanford-corenlp-docker.git
#    build:
#        context: https://github.com/NLPbox/stanford-corenlp-docker
#    image: corenlp:latest
#    ports:
#      - "9000:9000"
#    environment:
#      ANNOTATORS: tokenize,ssplit,pos,lemma,ner,depparse,coref,natlog,openie,parse,relation

  corenlp:
    build:
      dockerfile: docker/corenlp/Dockerfile
    image: corenlp:latest
    ports:
      - "${CORENLP_EXPOSE_PORT:-}:9000"
    environment:
      ANNOTATORS: tokenize,ssplit,pos,lemma,ner,depparse,coref,natlog,openie,parse,relation,kbp

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: rabbitmq
    user: rabbitmq
    profiles:
      - local
    ports:
      - "5672:5672"
      - "15672:15672"  # management UI
    volumes:
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./docker/rabbitmq/advanced.config:/etc/rabbitmq/advanced.config
      - ./docker/rabbitmq/definitions.file.json:/etc/rabbitmq/definitions.file.json
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
      start_interval: 5s

  # 8.x supported by ESS 3
  elasticsearch8:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch8
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-XX:UseSVE=0 -Xms750m -Xmx750m'
      - 'CLI_JAVA_OPTS=-XX:UseSVE=0'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    restart: always
    profiles:
      - local

  ess3:
    container_name: ess3
    hostname: ess3
    image: ${DOCKER_REGISTRY}/dpaas-internal/ess/ess-3:1.2.6
    volumes:
      - ./etc/pki:/opt/common/pki
      - ./etc/es/v8/omsb-node-document-index.json:/omsb-node-document-index.json
    environment:
      WHITELIST_ENTRIES: ${MEME_WHITELIST}
      ADMIN_TOKENS: ${MEME_WHITELIST}
      COM_DECIPHERNOW_SERVER_CONFIG_TLS_KEYSTORE: /opt/common/pki/twlserver.jks
      COM_DECIPHERNOW_SERVER_CONFIG_TLS_TRUSTSTORE: /opt/common/pki/truststore.jks
      SSL_KEYSTORE_PATH: /opt/common/pki/twlserver.jks
      SSL_TRUSTSTORE_PATH: /opt/common/pki/truststore.jks
      CLOUDSHARE_KEYSTORE: /opt/common/pki/twlserver.jks
      CLOUDSHARE_TRUSTSTORE: /opt/common/pki/truststore.jks
      CTE_USERSERVICE_KEYSTORE: /opt/common/pki/twlserver.jks
      CTE_USERSERVICE_TRUSTSTORE: /opt/common/pki/truststore.jks
      ZK_SSL_KEYSTORE_PATH: /opt/common/pki/twlserver.jks
      ZK_SSL_TRUSTSTORE_PATH: /opt/common/pki/truststore.jks
      SEARCH_KEYSTORE_PATH: /opt/common/pki/twlserver.jks
      SEARCH_TRUSTSTORE_PATH: /opt/common/pki/truststore.jks
      GOV_IC_CTE_SERVER_CONFIG_TLS_KEYSTORE: /opt/common/pki/twlserver.jks
      GOV_IC_CTE_SERVER_CONFIG_TLS_TRUSTSTORE: /opt/common/pki/truststore.jks
      GOV_IC_CTE_CHM_USER_COMMON_CONFIG_ZKKEYSTORE: /opt/common/pki/twlserver.jks
      GOV_IC_CTE_CHM_USER_COMMON_CONFIG_ZKTRUSTSTORE: /opt/common/pki/truststore.jks
      COM_TWITTER_FINATRA_CONFIG_KEYPATH: /opt/common/pki/twlserver.jks
      COM_TWITTER_FINATRA_CONFIG_CERTIFICATEPATH: /opt/common/pki/truststore.jks
      AAC_HOST: http://aac2:3000
      BANNED_PARAMS: query,q
      ES_HOSTS: http://elasticsearch8:9200
      HOST: 0.0.0.0
      LOG_LEVEL: info
      PORT: 3000
      SNIPPET_TYPE: elasticsearch8
      WAIT_HOSTS: elasticsearch8:9200
      PUT_URL_PATTERNS: /es/{index},/es/{index}/_doc/{id}
      POST_URL_PATTERNS: /es/{index}/_doc/{id},/es/{index}/_update/{id},/es/{index}/_delete_by_query
      DELETE_URL_PATTERNS: /es/{index},/es/{index}/_doc/{id}
      HEAD_URL_PATTERNS: /es/{index}
    command:
      - /bin/bash
      - -c
      - |
        echo "waiting for elasticsearch8..."
        until curl -sS "http://elasticsearch8:9200/_cat/health?h=status" | grep -q "green\|yellow"; do
          sleep 1
        done
        sleep 10

        echo "inserting omsb_node_index..."
        curl -v -X PUT "http://elasticsearch8:9200/omsb_node_index" -H "Content-Type: application/json" -d @/omsb-node-document-index.json

        /app/ess
    ports:
      - "7399:3000"
    depends_on:
      - aac2
      - elasticsearch8
    profiles:
      - local

  ess-indexer-service:
    image: ${DOCKER_REGISTRY}/aio4/dev/services/oms/oms-bridge:${OMSB_VERSION}
    container_name: ess-indexer-service
    env_file:
      - docker/local/docker.env
    environment:
      - OMSB_SERVICE=ess-indexer
      - OMSB_ENABLE_LIQUIBASE=false
      - POSTGRES_HOST=postgis
    volumes:
      - ./etc/pki:/opt/oms-bridge/pki
      - ./etc/whitelist.txt:/opt/oms-bridge/etc/config/external/Whitelist.txt
      - ./etc/config/external/CollectionStatusThresholds.yaml:/opt/oms-bridge/etc/config/external/CollectionStatusThresholds.yaml
    depends_on:
      omsb-init:
        condition: service_started
      ess3:
        condition: service_started
      postgis:
        condition: service_healthy
    restart: on-failure:3
    profiles:
      - local

volumes:
  doccano-db:
  localstack:
  pgadmin:
  postgis:
  elasticsearch:

secrets:
  mynetrc:
    file: ${HOME}/.netrc
