services:
  oms_sensemaking:
    build:
      context: .
      secrets:
        - mynetrc
      args:
        PIP_INDEX_URL: ${PIP_INDEX}
        PIP_EXTRA_INDEX_URL: ${PIP_EXTRA_INDEX}
    ports:
      - 5001:${UVICORN_PORT:-8443}
    environment:
      # database config
      DB_HOST: postgis
      DB_USER: ${DB_USER:-${PGUSER:-appuser}}
      DB_PASSWORD: ${DB_PASSWORD:-${PGPASSWORD}}
      DB_SSL: ${DB_SSL:-true}
      PGHOST: postgis
      UVICORN_PORT: ${UVICORN_PORT:-8443}
      UVICORN_SSL_KEYFILE: ${UVICORN_SSL_KEYFILE}
      UVICORN_SSL_CERTFILE: ${UVICORN_SSL_CERTFILE}
      UVICORN_SSL_CERT_REQS: ${UVICORN_SSL_CERT_REQS:-0}  # set this to 1 to request client certs
      UVICORN_LOG_LEVEL: ${UVICORN_LOG_LEVEL:-info}

      # misc.
      APP_LOG_LEVEL: ${APP_LOG_LEVEL:-INFO}
      RELOAD_APP: ${RELOAD_APP:-1}
      
      # OpenTelemetry configuration
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
      OTEL_SERVICE_NAME: oms-sensemaking
      OTEL_TRACES_SAMPLER: always_on
    volumes:
      - .:/app
      - ./etc/pki:/opt/common/pki
    healthcheck:
      test: ["CMD-SHELL", "/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    depends_on:
      - postgis

  postgis:
    image: postgis/postgis:17-3.5-alpine
    platform: linux/amd64  # see https://github.com/postgis/docker-postgis/issues/216
    ports:
      - "${POSTGRES_PORT:-}:5432"
    environment:
      # Admin user
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      # Application user
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      # Database names
      DB_NAME: ${DB_NAME}
      DB_NAME_OMSB: ${DB_NAME_OMSB}
      DB_TEMPLATE: ${DB_TEMPLATE}

      # SSL certs
      UVICORN_SSL_KEYFILE: ${UVICORN_SSL_KEYFILE}
      UVICORN_SSL_CERTFILE: ${UVICORN_SSL_CERTFILE}
    volumes:
      - postgis:/var/lib/postgresql/data
      - ./etc/pki:/opt/common/pki:rw
      - ./docker/postgis/initdb.d/20_oms-sensemaking.sh:/docker-entrypoint-initdb.d/20_oms-sensemaking.sh
      - ./docker/postgis/initdb.d/30_enable-ssl.sh:/docker-entrypoint-initdb.d/30_enable-ssl.sh
      - ./docker/postgis/initdb.d/40_enable-extensions.sh:/docker-entrypoint-initdb.d/40_enable-extensions.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    profiles:
      - dev
    image: dpage/pgadmin4:9.8
    volumes:
      - ./docker/postgis/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-dev@blackcape.io}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-$POSTGRES_PASSWORD}
      PGADMIN_CONFIG_LOGIN_BANNER: "${PGADMIN_CONFIG_LOGIN_BANNER:-'<h4>Development Database</h4>'}"
    ports:
      - 5050:80
    depends_on:
      - postgis

  omsb-init:
    image: ${DOCKER_REGISTRY}/aio4/dev/services/oms/oms-bridge:${OMSB_VERSION}
    container_name: omsb-init
    env_file:
      - ./docker/omsb/omsb.env
    environment:
      OMSB_SERVICE: init
      OMSB_ENABLE_LIQUIDBASE: true
      POSTGRES_PASSWORD:
    volumes:
      - ./etc/pki:/opt/oms-bridge/pki
    depends_on:
      postgis:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      aac2:
        condition: service_started
    profiles:
      - local

  # NOTE: The omsb container should not require the "guide" service,
  #       but it may try to resolve the hostnames, which results in a stack
  #       trace being logged. This can be ignored, since the purpose of this
  #       configuration is to provide a minimal omsb for development & testing.
  omsb2:
    image: ${DOCKER_REGISTRY}/aio4/dev/services/oms/oms-bridge:${OMSB_VERSION}
    environment:
      # PostgreSQL/PostGIS variables
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD:
      OMSB_SERVICE: api
    env_file:
      - ./docker/omsb/omsb.env
    volumes:
      - ./etc/pki:/opt/oms-bridge/pki
      - ./etc/whitelist.txt:/opt/oms-bridge/etc/config/external/Whitelist.txt
      - ./docker/omsb/LocalCollectionStatusThresholds.yaml:/opt/oms-bridge/etc/collectionstatus/CollectionStatusThresholds.yaml
      - ./docker/omsb/SystemLabels.yaml:/opt/oms-bridge/etc/config/external/SystemLabels.yaml
    ports:
      - "8010:8000"
      - "8020:8443"
    depends_on:
      postgis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      omsb-init:
        condition: service_started
    profiles:
      - local

  aac2:
#    hostname: aac2
#    container_name: aac2
    image: ${DOCKER_REGISTRY}/dpaas-internal/aac/ent-aac-service:2.1.15.3
    command: sh -c "./entrypoint.sh"
    volumes:
      - ./etc/pki:/opt/common/pki
      - ./docker/aac2/entrypoint.sh:/app/entrypoint.sh
      - ./docker/aac2/users:/app/users
    ports:
      - "5022:3000"
    environment:
      HOST_URL: 0.0.0.0:3000
      DEVELOPMENT_MODE: "true"
      ENABLE_L1_CACHE_SYNC: "false"
      HOST_TLS_CERT_FILE: /opt/common/pki/server.public
      HOST_TLS_KEY_FILE: /opt/common/pki/server.private
      TEMPLATES_PARSE_INTERVAL: 15s
    profiles:
      - local

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: rabbitmq
    user: rabbitmq
    profiles:
      - local
    ports:
      - "5672:5672"
      - "15672:15672"  # management UI
    volumes:
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./docker/rabbitmq/advanced.config:/etc/rabbitmq/advanced.config
      - ./docker/rabbitmq/definitions.file.json:/etc/rabbitmq/definitions.file.json
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
      start_interval: 5s

  # 8.x supported by ESS 3
  elasticsearch8:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch8
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-XX:UseSVE=0 -Xms750m -Xmx750m'
      - 'CLI_JAVA_OPTS=-XX:UseSVE=0'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    restart: always
    profiles:
      - local

  ess3:
    container_name: ess3
    hostname: ess3
    image: ${DOCKER_REGISTRY}/aio4/dev/services/oms/oms-ess-3:1.2.7
    volumes:
      - ./etc/pki:/opt/common/pki
      - ./etc/es/v8/omsb-node-document-index.json:/omsb-node-document-index.json
    environment:
      WHITELIST_ENTRIES: ${MEME_WHITELIST}
      ADMIN_TOKENS: ${MEME_WHITELIST}
      COM_DECIPHERNOW_SERVER_CONFIG_TLS_KEYSTORE: /opt/common/pki/twlserver.jks
      COM_DECIPHERNOW_SERVER_CONFIG_TLS_TRUSTSTORE: /opt/common/pki/truststore.jks
      SSL_KEYSTORE_PATH: /opt/common/pki/twlserver.jks
      SSL_TRUSTSTORE_PATH: /opt/common/pki/truststore.jks
      CLOUDSHARE_KEYSTORE: /opt/common/pki/twlserver.jks
      CLOUDSHARE_TRUSTSTORE: /opt/common/pki/truststore.jks
      CTE_USERSERVICE_KEYSTORE: /opt/common/pki/twlserver.jks
      CTE_USERSERVICE_TRUSTSTORE: /opt/common/pki/truststore.jks
      ZK_SSL_KEYSTORE_PATH: /opt/common/pki/twlserver.jks
      ZK_SSL_TRUSTSTORE_PATH: /opt/common/pki/truststore.jks
      SEARCH_KEYSTORE_PATH: /opt/common/pki/twlserver.jks
      SEARCH_TRUSTSTORE_PATH: /opt/common/pki/truststore.jks
      GOV_IC_CTE_SERVER_CONFIG_TLS_KEYSTORE: /opt/common/pki/twlserver.jks
      GOV_IC_CTE_SERVER_CONFIG_TLS_TRUSTSTORE: /opt/common/pki/truststore.jks
      GOV_IC_CTE_CHM_USER_COMMON_CONFIG_ZKKEYSTORE: /opt/common/pki/twlserver.jks
      GOV_IC_CTE_CHM_USER_COMMON_CONFIG_ZKTRUSTSTORE: /opt/common/pki/truststore.jks
      COM_TWITTER_FINATRA_CONFIG_KEYPATH: /opt/common/pki/twlserver.jks
      COM_TWITTER_FINATRA_CONFIG_CERTIFICATEPATH: /opt/common/pki/truststore.jks
      AAC_HOST: http://aac2:3000
      BANNED_PARAMS: query,q
      ES_HOSTS: http://elasticsearch8:9200
      HOST: 0.0.0.0
      LOG_LEVEL: info
      PORT: 3000
      SNIPPET_TYPE: elasticsearch8
      WAIT_HOSTS: elasticsearch8:9200
      GET_URL_PATTERNS: /es/{index}/_refresh,/es/_cluster/health
      PUT_URL_PATTERNS: /es/{index},/es/{index}/_doc/{id}
      POST_URL_PATTERNS: /es/{index}/_doc/{id},/es/{index}/_update/{id},/es/{index}/_delete_by_query
      DELETE_URL_PATTERNS: /es/{index},/es/{index}/_doc/{id}
      HEAD_URL_PATTERNS: /es/{index}
    command:
      - /bin/bash
      - -c
      - |
        echo "waiting for elasticsearch8..."
        until curl -sS "http://elasticsearch8:9200/_cat/health?h=status" | grep -q "green\|yellow"; do
          sleep 1
        done
        sleep 10

        echo "inserting omsb_node_index..."
        curl -v -X PUT "http://elasticsearch8:9200/omsb_node_index" -H "Content-Type: application/json" -d @/omsb-node-document-index.json

        /app/ess
    ports:
      - "7399:3000"
    depends_on:
      - aac2
      - elasticsearch8
    profiles:
      - local

  ess-indexer-service:
    image: ${DOCKER_REGISTRY}/aio4/dev/services/oms/oms-bridge:${OMSB_VERSION}
    container_name: ess-indexer-service
    env_file:
      - docker/local/docker.env
    environment:
      - OMSB_SERVICE=ess-indexer
      - OMSB_ENABLE_LIQUIBASE=false
      - POSTGRES_HOST=postgis
    volumes:
      - ./etc/pki:/opt/oms-bridge/pki
      - ./etc/whitelist.txt:/opt/oms-bridge/etc/config/external/Whitelist.txt
      - ./etc/config/external/CollectionStatusThresholds.yaml:/opt/oms-bridge/etc/config/external/CollectionStatusThresholds.yaml
    depends_on:
      omsb-init:
        condition: service_started
      ess3:
        condition: service_started
      postgis:
        condition: service_healthy
    restart: on-failure:3
    profiles:
      - local

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" 
    volumes:
      - './docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml' # Custom config
      - 'prometheus_data:/prometheus'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
      - '--web.enable-otlp-receiver'
      - '--enable-feature=native-histograms'
    restart: always
    profiles:
      - metrics

  grafana:
    image: grafana/grafana:12.0.0
    container_name: grafana
    restart: always
    ports:
      - "3001:3000" 
    env_file:
      - docker/grafana/grafana.env
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}
      - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED}
      - GF_AUTH_ORG_ROLE=${GF_AUTH_ORG_ROLE}
    volumes:
      - "./docker/grafana/dashboards/:/etc/grafana/provisioning/dashboards/"
      - "./docker/grafana/datasources/:/etc/grafana/provisioning/datasources/"
      - "./docker/grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "grafana_data:/var/lib/grafana"
    depends_on:
      - prometheus 
      - tempo
    profiles:
      - metrics

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - "./docker/tempo/tempo.yaml:/etc/tempo.yaml"
    ports:
      - "3200:3200"   # tempo
      - "4317:4317"   # otlp grpc
      - "4318:4318"   # otlp http
    profiles:
      - metrics
  sonarqube:
    container_name: sonarqube
    image: ${DOCKER_REGISTRY}/sonarqube:9.9.8-community
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
    ports:
      - "9900:9000"
    profiles:
      - tools

volumes:
  pgadmin:
  postgis:
  elasticsearch:
  prometheus_data:
  grafana_data:

secrets:
  mynetrc:
    file: ${HOME}/.netrc
