services:
  oms_sensemaking:
    build:
      context: .
      secrets:
        - mynetrc
    ports:
      - 5001:${UVICORN_PORT:-8443}
    environment:
      # AWS
      AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL:-http://localstack:4566}
      # database config
      DB_HOST: postgis
      DB_USER: ${DB_USER:-${PGUSER:-appuser}}
      DB_PASSWORD: ${DB_PASSWORD:-${PGPASSWORD}}
      DB_SSL: ${DB_SSL:-true}
      PGHOST: postgis
      UVICORN_PORT: ${UVICORN_PORT:-8443}
      UVICORN_SSL_KEYFILE: ${UVICORN_SSL_KEYFILE}
      UVICORN_SSL_CERTFILE: ${UVICORN_SSL_CERTFILE}
      UVICORN_SSL_CERT_REQS: ${UVICORN_SSL_CERT_REQS:-0}  # set this to 1 to request client certs
      UVICORN_LOG_LEVEL: ${UVICORN_LOG_LEVEL:-info}

      # misc.
      APP_LOG_LEVEL: ${APP_LOG_LEVEL:-INFO}
      RELOAD_APP: ${RELOAD_APP:-1}
    volumes:
      - .:/app
      - ./etc/pki:/opt/common/pki
    healthcheck:
      test: ["CMD-SHELL", "/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    depends_on:
      - postgis

  postgis:
    image: postgis/postgis:16-3.4-alpine
    platform: linux/amd64  # see https://github.com/postgis/docker-postgis/issues/216
    ports:
      - "${POSTGRES_PORT:-}:5432"
    environment:
      # PostgreSQL/PostGIS variables
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD:

      # psql variables
      PGUSER: ${PGUSER:-${POSTGRES_USER:-postgres}}
      PGPASSWORD: ${PGPASSWORD:-$POSTGRES_PASSWORD}
      PGDATABASE: ${PGDATABASE:-oms_sensemaking}
    volumes:
      - postgis:/var/lib/postgresql/data
      - ./etc/pki:/opt/common/pki:ro
      - ./docker/postgis/initdb.d/20_oms-sensemaking.sql:/docker-entrypoint-initdb.d/20_oms-sensemaking.sql
      - ./docker/postgis/initdb.d/30_enable-ssl.sh:/docker-entrypoint-initdb.d/30_enable-ssl.sh
      - ./docker/postgis/initdb.d/40_init.sql:/docker-entrypoint-initdb.d/40_init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    profiles:
      - dev
    image: dpage/pgadmin4:8
    volumes:
      - ./docker/postgis/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-dev@blackcape.io}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-$POSTGRES_PASSWORD}
      PGADMIN_CONFIG_LOGIN_BANNER: "${PGADMIN_CONFIG_LOGIN_BANNER:-'<h4>Development Database</h4>'}"
    ports:
      - 5050:80
    depends_on:
      - postgis

  omsb-init:
    image: tex.gerbil-cloud.ts.net:5000/aio4/dev/services/oms/oms-bridge:${OMSB_VERSION}
    container_name: omsb-init
    env_file:
      - ./docker/omsb/omsb.env
    environment:
      OMSB_SERVICE: init
      OMSB_ENABLE_LIQUIDBASE: true
      POSTGRES_PASSWORD:
    volumes:
      - ./etc/pki:/opt/oms-bridge/pki
    depends_on:
      postgis:
        condition: service_healthy
      localstack:
        condition: service_started
      rabbitmq:
        condition: service_started
      aac2:
        condition: service_started
    profiles:
      - local

  # NOTE: The omsb container should not require the "ess" or "guide" services,
  #       but it may try to resolve the hostnames, which results in a stack
  #       trace being logged. This can be ignored, since the purpose of this
  #       configuration is to provide a minimal omsb for development & testing.
  omsb2:
    image: tex.gerbil-cloud.ts.net:5000/aio4/dev/services/oms/oms-bridge:${OMSB_VERSION}
    environment:
      # PostgreSQL/PostGIS variables
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD:
      OMSB_SERVICE: api
    env_file:
      - ./docker/omsb/omsb.env
    volumes:
      - ./etc/pki:/opt/oms-bridge/pki
      - ./etc/whitelist.txt:/opt/oms-bridge/etc/whitelist.txt
      - ./docker/omsb/LocalCollectionStatusThresholds.yaml:/opt/oms-bridge/etc/collectionstatus/CollectionStatusThresholds.yaml
      - ./docker/omsb/SystemLabels.yaml:/opt/oms-bridge/etc/config/external/SystemLabels.yaml
      - ./docker/omsb/Classes.csv:/opt/oms-bridge/etc/ontology/Classes.csv  # TODO remove
    ports:
      - "8010:8000"
      - "8020:8443"
    depends_on:
      postgis:
        condition: service_started
      localstack:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      omsb-init:
        condition: service_started
    profiles:
      - local

  localstack:
    hostname: localstack
    image: localstack/localstack:3.4.0
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - OMSB_SQS_QUEUE_CONFIG=geoSensemakerTrigger,inferenceSensemakerTrigger,resolutionTrigger,milSymbolTrigger
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./docker/localstack:/etc/localstack/init/ready.d"
    profiles:
      - local

  aac2:
#    hostname: aac2
#    container_name: aac2
    image: tex.gerbil-cloud.ts.net:5000/dpaas-internal/aac/ent-aac-service:2.1.15.3
    command: sh -c "./entrypoint.sh"
    volumes:
      - ./etc/pki:/opt/common/pki
      - ./docker/aac2/entrypoint.sh:/app/entrypoint.sh
      - ./docker/aac2/users:/app/users
    ports:
      - "5022:3000"
    environment:
      HOST_URL: 0.0.0.0:3000
      DEVELOPMENT_MODE: "true"
      ENABLE_L1_CACHE_SYNC: "false"
      HOST_TLS_CERT_FILE: /opt/common/pki/server.public
      HOST_TLS_KEY_FILE: /opt/common/pki/server.private
      TEMPLATES_PARSE_INTERVAL: 15s
    profiles:
      - local

  doccano:
    image: doccano/doccano
    ports:
      - "8000:8000"
    environment:
      ADMIN_USERNAME: admin
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: password
    volumes:
     - doccano-db:/data
    profiles:
      - local

#  corenlp:
#    command: docker buildx build -t corenlp https://github.com/NLPbox/stanford-corenlp-docker.git
#    build:
#        context: https://github.com/NLPbox/stanford-corenlp-docker
#    image: corenlp:latest
#    ports:
#      - "9000:9000"
#    environment:
#      ANNOTATORS: tokenize,ssplit,pos,lemma,ner,depparse,coref,natlog,openie,parse,relation

  corenlp:
    build:
      dockerfile: docker/corenlp/Dockerfile
    image: corenlp:latest
    ports:
      - "${CORENLP_EXPOSE_PORT:-}:9000"
    environment:
      ANNOTATORS: tokenize,ssplit,pos,lemma,ner,depparse,coref,natlog,openie,parse,relation,kbp

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: rabbitmq
    user: rabbitmq
    profiles:
      - local
    ports:
      - "5672:5672"
      - "15672:15672"  # management UI
    volumes:
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./docker/rabbitmq/advanced.config:/etc/rabbitmq/advanced.config
      - ./docker/rabbitmq/definitions.file.json:/etc/rabbitmq/definitions.file.json
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
      start_interval: 5s

volumes:
  doccano-db:
  localstack:
  pgadmin:
  postgis:

secrets:
  mynetrc:
    file: ${HOME}/.netrc
