# ruff.toml --- ruff configuration.
line-length = 120
target-version = 'py310'


[lint]
select = [
    'B',      # flake8-bugbear
    'SIM',    # flake8-simplify
    'I',      # isort
    'N',      # pep8-naming
#    'D',      # pydocstyle
    'E',      # pycodestyle errors
    'W',      # pycodestyle warnings
    'F',      # Pyflakes
#    'UP',     # pyupgrade
]

# ingoring some linting rules for compatibility with the ruff formatter
# see https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
ignore = [
    'D105',  # undocumented-magic-method
    'E111',  # indentation-with-invalid-multiple
    'E114',  # indentation-with-invalid-multiple-comment
    'E117',  # over-indented
    'W191'   # tab-indentation
]


[lint.pydocstyle]
convention = 'pep257'  # Accepts: "google", "numpy", or "pep257".


[lint.per-file-ignores]
# Ignore `E402` (import violations) where dotenv is being used
'__main__.py' = ['E402']
'conftest.py' = ['E402']

# Ignore `F403` (undefined-local-with-import-star) in Alembic environment config
'migrations/env.py' = ['F403']

# Ignore `N803` (invalid-argument-name) in OMS audit log events
'**/core/events.py' = ['N803']

# Ignore `E501` (line too long) in mock responses
'tests/nlp/mock_responses.py' = ['E501']

[format]
docstring-code-format = true
docstring-code-line-length = 50

exclude = [
    'config.py'
]
