PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>
PREFIX ingest_omsb_graphmart: <http://cambridgesemantics.com/Layer/1f3cbffb3f734b0193ab88e3f0e55c81/Model#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX modeled: <https://blackcape.io/2025/01/omsdiekm/>

## In order for the numerous mapping layers to connect their resources, we need to align on how to construct node_ids
## Its possible to use the node source record id as the node id, but will this work when we need to match ends of relationships? 

INSERT {
    GRAPH ${targetGraph} {
      # make obj an instance of the class OBI specified as given in OMSDB
      ?instance a ?class ;
      	rdfs:label ?node_name ;
        ?attribute_to_datatype_property ?attribute_value ; 
        ?R2L_object_prop ?R2L_node_instance; 
        ?L2R_object_prop ?L2R_node_instance ;
        ?allegiance_object_property ?allegiance_country_instance 
      .   
        ?allegiance_country_instance a ?cco_country_class .
        ?attribute_to_datatype_property a owl:DatatypeProperty.
        ?R2L_object_prop a owl:ObjectProperty.
        ?L2R_object_prop a owl:ObjectProperty.   
        ?allegiance_object_property a owl:ObjectProperty. 
        ?allegiance_country_instance rdfs:label ?allegiance_object_string . 
    }
}
WHERE { 
  GRAPH <http://cambridgesemantics.com/Layer/1f3cbffb3f734b0193ab88e3f0e55c81> {
	?node_record_uri ingest_omsb_graphmart:Node.class_iri ?object_class_iri  ;
        # flagging for viewers that I don't have to use OPTIONAL below
        # bc I know that both name & id are NOT NULL fields in the node table 
        # from which these objects were created.
		ingest_omsb_graphmart:Node.name ?node_name ;
        ingest_omsb_graphmart:Node.id ?node_id ;  ## this variable connects most objects together 
        ingest_omsb_graphmart:Node.allegiance ?allegiance_object_string ; 

        # The list below is based on whatever IRIs we have in omsb-latest's node table right now.
    ## when the models are loaded, we filter on all subclasses of our top-level class or some subset thereof
    FILTER (?object_class_iri IN (
        "http://www.ontologyrepository.com/CommonCoreOntologies/Organization"
    ) ) .


    OPTIONAL {    ?observation_obj ingest_omsb_graphmart:Observation.node_id ?node_id  ;
		ingest_omsb_graphmart:Observation.geometry ?observed_geometry .
        ## other observational connections here
    }  

    
    # any attribute for now is assumed to be a datatype property in OWL
    OPTIONAL {    ?attribute_record ingest_omsb_graphmart:Attribute.node_id ?node_id  ;
                  ingest_omsb_graphmart:Attribute.attribute_value ?attribute_value ;  ## untyped for now
                  ingest_omsb_graphmart:Attribute.attribute_iri ?attribute_iri .
      			  BIND(IRI(?attribute_iri) as ?attribute_to_datatype_property)
    }
    # We rely on the integrity of the RDB and do not ensure that start_node <> end_node (do self-referentials exist?)
    # focus as start node L2R
    OPTIONAL {    
      ?relationship_record ingest_omsb_graphmart:Relationship.start_node_id ?node_id  ;
				  ## will catch this ?object_of_relationship_node_id as it is formed in another layer not in this layer
                  ## we only care about organizations here
                  ingest_omsb_graphmart:Relationship.end_node_id ?L2R_node_id ;
                  ingest_omsb_graphmart:Relationship.object_property_iri ?L2R_obj_prop_iri .
		          # FILTER (?ctrldby_relationship_iri IN (        ) ) .
                  BIND(IRI(CONCAT("https://blackcape.io/2025/01/omsdiekm/",?L2R_node_id)) AS ?L2R_node_instance )
      			  BIND(IRI(?L2R_obj_prop_iri) as ?L2R_object_prop) 
    }      
    # focus from end_node R2L
    OPTIONAL {    
      ?relationship_record ingest_omsb_graphmart:Relationship.end_node_id ?node_id  ;
				  ## will catch this ?object_of_relationship_node_id as it is formed in another layer not in this layer
                  ## we only care about organizations here
                  ingest_omsb_graphmart:Relationship.start_node_id ?R2L_node_id ;
                  ingest_omsb_graphmart:Relationship.object_property_iri ?R2L_obj_prop_iri .
		          # FILTER (?ctrldby_relationship_iri IN (        ) ) .
                  BIND(IRI(CONCAT("https://blackcape.io/2025/01/omsdiekm/",?R2L_node_id)) AS ?R2L_node_instance )
      			  BIND(IRI(?R2L_obj_prop_iri) as ?R2L_object_prop) 
    }    
    

    # Using a tex-latest OMSB2 IRIs for now (see spreadsheet at
    # https://docs.google.com/spreadsheets/d/1cajOVDD4yBVJCdNBYLy5PsZIfyRZG-57ujJjvXklBEw/edit)
    BIND(IRI(?object_class_iri) AS ?class)
    #BIND(IRI("http://schema.dia.mil/DefenseIntelligenceCoreOntology/controlledBy") AS ?controlled_by)
    #BIND(IRI("http://purl.obolibrary.org/obo/BFO_0000196") AS ?bearer_of)
    BIND(IRI("https://foundry.ai.mil/MIDB_GST/v1/Located_At") AS ?located_at)
    #BIND(IRI("http://purl.obolibrary.org/obo/BFO_0000176") AS ?continuant_part_of_at_some_time)
    #BIND(IRI("http://schema.dia.mil/DefenseIntelligenceCoreOntology/hasOperationalStatus") AS ?operational_status)
    BIND (IRI ( CONCAT ( "https://blackcape.io/2025/01/omsdiekm/", ?node_id)) as ?instance) 
    BIND(IRI("http://www.ontologyrepository.com/CommonCoreOntologies/Country") as ?cco_country_class)
    BIND(IRI(CONCAT("https://blackcape.io/2025/01/omsdiekm/tempspace/", ?allegiance_object_string)) as ?allegiance_country_instance)  
    BIND(IRI("https://foundry.ai.mil/INDOPACOM/v5/Allegiance") as ?allegiance_object_property)
  }
}
