PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>
PREFIX ingest_omsb_graphmart: <http://cambridgesemantics.com/Layer/1f3cbffb3f734b0193ab88e3f0e55c81/Model#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

INSERT {
    GRAPH ${targetGraph} {
      # make obj an instance of the class OBI specified for EQP
      ?node_obj a ?equip_class ;
      # effectively create a data property (as opposed to an obj property) for the name
      	rdfs:label ?node_name .
    }
}
WHERE {
  GRAPH <http://cambridgesemantics.com/Layer/1f3cbffb3f734b0193ab88e3f0e55c81> {
	?node_obj ingest_omsb_graphmart:Node.class_iri ?object  ;
		ingest_omsb_graphmart:Node.name ?node_name ;
        # The list below is based on whatever IRIs we have in omsb-latest's node table right now.
    FILTER (?object IN (
        "http://schema.dia.mil/DefenseIntelligenceCoreOntology/EquipmentItem", 
        "http://www.ontologyrepository.com/CommonCoreOntologies/Aircraft",
        "http://omsb/test/Tank",
        "http://omsb/test/Plane",
        "http://omsb/test/Helicopter",
        "https://foundry.ai.mil/NIEM/v5.2/AircraftType",
        "https://foundry.ai.mil/NIEM/v5.2/VesselType",
        "https://foundry.ai.mil/NIEM/v5.2/PleasureCraftCodeType"
    ) ) 
  
    # Using a tex-latest OMSB2 IRI for now (see spreadsheet at
    # https://docs.google.com/spreadsheets/d/1cajOVDD4yBVJCdNBYLy5PsZIfyRZG-57ujJjvXklBEw/edit)
    BIND(IRI("http://schema.dia.mil/DefenseIntelligenceCoreOntology/EquipmentItem") AS ?equip_class)
  }
}
