PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>
PREFIX ingest_omsb_graphmart: <http://cambridgesemantics.com/Layer/1f3cbffb3f734b0193ab88e3f0e55c81/Model#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

INSERT {
    GRAPH ${targetGraph} {
      ?node_obj a ?structure_facility_class ;
      rdfs:label ?node_name ;
      ?operational_status ?status ;
      ?bearer_of ?function ;
      ?controlled_by ?controlling_obj_id1 ;
      ?controlled_by ?controlling_obj_id2 ;
      ?has_continuant_part_at_some_time ?cont_part_obj_id1 ;
      ?has_continuant_part_at_some_time ?cont_part_obj_id2 .
    }
}
WHERE {
  ## REMOVING HARDCODED GRAPH URI 20250225
  ## GRAPH <http://cambridgesemantics.com/Layer/1f3cbffb3f734b0193ab88e3f0e55c81> {
	?node_obj ingest_omsb_graphmart:Node.class_iri ?class_iri  ;
		ingest_omsb_graphmart:Node.name ?node_name ;
        ingest_omsb_graphmart:Node.id ?node_id ;

    FILTER (?class_iri IN (
        "http://schema.dia.mil/DefenseIntelligenceCoreOntology/StructureFacility", 
        "http://schema.dia.mil/DefenseIntelligenceCoreOntology/FixedStructure", 
        "http://schema.dia.mil/DefenseIntelligenceCoreOntology/Building",
        "http://schema.dia.mil/DefenseIntelligenceCoreOntology/Revetment"
      ) ) .
    
    ##########
    # STATUS #
    #########
    OPTIONAL {
      ?attribute_obj ingest_omsb_graphmart:Attribute.node_id ?node_id ;
      	ingest_omsb_graphmart:Attribute.attribute_value ?status ;
        ingest_omsb_graphmart:Attribute.attribute_iri ?attribute_iri ;
     FILTER(?attribute_iri IN (
          "https://foundry.ai.mil/DICO/v3.1.0/Operational_Status", 
          "https://foundry.ai.mil/INDOPACOM/v5/Operational_Status",
          "https://foundry.ai.mil/MIDB_GST/v1/Operational_Status",
          "https://foundry.ai.mil/DICO/v3.1.0/Status",
          "https://foundry.ai.mil/INDOPACOM/v5/Status",
          "https://foundry.ai.mil/MIDB_GST/v1/Status"
          # More to follow ...
        ) ) .
    }
    ############
    # FUNCTION #
    ###########
    OPTIONAL {    ?funct_attribute_obj ingest_omsb_graphmart:Attribute.node_id ?node_id  ;
                  ingest_omsb_graphmart:Attribute.attribute_value ?function ;
                  ingest_omsb_graphmart:Attribute.attribute_iri ?funct_attribute_iri ;
      FILTER (?funct_attribute_iri IN (
          "https://foundry.ai.mil/INDOPACOM/v5/Function", 
          "https://foundry.ai.mil/INDOPACOM/v5/Function_Primary",
          "https://foundry.ai.mil/INDOPACOM/v5/Object_Role_or_Function",
          "https://foundry.ai.mil/INDOPACOM/v5/Secondary_Function",
          "https://foundry.ai.mil/MIDB_GST/v1/Function",
          "https://foundry.ai.mil/MIDB_GST/v1/Primary_Function",
          "https://foundry.ai.mil/MIDB_GST/v1/Function_Primary",
          "https://foundry.ai.mil/MIDB_GST/v1/Function_Secondary",
          "https://foundry.ai.mil/MIDB_GST/v1/Object_Role_or_Function"
      ) )
    }
    #################
    # CONTROLLED BY # (ie. my node is "controlled by" another node)
    ################
    OPTIONAL {	?ctrldby_relationship_obj ingest_omsb_graphmart:Relationship.start_node_id ?node_id ;
      			ingest_omsb_graphmart:Relationship.end_node_id ?controlling_node_id1 ;
      			ingest_omsb_graphmart:Relationship.object_property_iri ?ctrldby_relationship_iri ;
      FILTER (?ctrldby_relationship_iri IN (
        "http://schema.dia.mil/DefenseIntelligenceCoreOntology/controlledBy",
        "https://foundry.ai.mil/MIDB/V3.3/is_commanded_or_controlled__by",
        "https://foundry.ai.mil/MIDB/V3.3/is_commanded_or_controlled_primarily_by"
          # More to follow ...
        )) .
      BIND(IRI(CONCAT("http://cambridgesemantics.com/Layer/1f3cbffb3f734b0193ab88e3f0e55c81/Node/",?controlling_node_id1)) AS ?controlling_obj_id1 )
    }
    
    ############
    # CONTROLS # (ie. another node "controls" my node)
    ###########
    OPTIONAL {	?ctrls_relationship_obj ingest_omsb_graphmart:Relationship.start_node_id ?controlling_node_id2 ;
      			ingest_omsb_graphmart:Relationship.end_node_id ?node_id ;
      			ingest_omsb_graphmart:Relationship.object_property_iri ?ctrls_relationship_iri ;
      FILTER (?ctrls_relationship_iri IN (
        "http://schema.dia.mil/DefenseIntelligenceCoreOntology/controls",
        "https://foundry.ai.mil/MIDB/V3.3/commands_or_controls",
        "https://foundry.ai.mil/MIDB/V3.3/commands_or_controls_primarily"
          # More to follow ...
        )) .
      BIND(IRI(CONCAT("http://cambridgesemantics.com/Layer/1f3cbffb3f734b0193ab88e3f0e55c81/Node/",?controlling_node_id2)) AS ?controlling_obj_id2 )
    }
    
    ######################
    # CONTINUANT PART OF # (ie. another node is "continuant part of" my node)
    #####################
    OPTIONAL {	?cont_part_of_rel_obj ingest_omsb_graphmart:Relationship.end_node_id ?node_id ;
      			ingest_omsb_graphmart:Relationship.start_node_id ?cont_part_node_id1 ;
      			ingest_omsb_graphmart:Relationship.object_property_iri ?cont_part_of_rel_iri ;
      FILTER (?cont_part_of_rel_iri IN (
          "http://purl.obolibrary.org/obo/BFO_0000176", #continuant part of at some time
          "http://purl.obolibrary.org/obo/BFO_0000177" #continuant part of at all times
          # More to follow ...
        )) .
      BIND(IRI(CONCAT("http://cambridgesemantics.com/Layer/1f3cbffb3f734b0193ab88e3f0e55c81/Node/",?cont_part_node_id1)) AS ?cont_part_obj_id1 )
    }
    
    ######################
    # HAS CONTINUANT PART # (ie. my node "has continuant part" that is another node)
    #####################
    OPTIONAL {	?has_cont_part_rel_obj ingest_omsb_graphmart:Relationship.end_node_id ?cont_part_node_id2 ;
      			ingest_omsb_graphmart:Relationship.start_node_id ?node_id ;
      			ingest_omsb_graphmart:Relationship.object_property_iri ?has_cont_part_rel_iri ;
      FILTER (?has_cont_part_rel_iri IN (
          "http://purl.obolibrary.org/obo/BFO_0000178", #has continuant part of at some time
          "http://purl.obolibrary.org/obo/BFO_0000110" #has continuant part of at all times
          # More to follow ...
        )) .
      BIND(IRI(CONCAT("http://cambridgesemantics.com/Layer/1f3cbffb3f734b0193ab88e3f0e55c81/Node/",?cont_part_node_id2)) AS ?cont_part_obj_id2 )
    }
    
    # Using a tex-latest OMSB2 IRIs for now (see spreadsheet at
    # https://docs.google.com/spreadsheets/d/1cajOVDD4yBVJCdNBYLy5PsZIfyRZG-57ujJjvXklBEw/edit)
    BIND(IRI("http://schema.dia.mil/DefenseIntelligenceCoreOntology/StructureFacility") AS ?structure_facility_class)
    BIND(IRI("http://schema.dia.mil/DefenseIntelligenceCoreOntology/controlledBy") AS ?controlled_by)
    BIND(IRI("http://purl.obolibrary.org/obo/BFO_0000196") AS ?bearer_of)
    BIND(IRI("http://purl.obolibrary.org/obo/BFO_0000178") AS ?has_continuant_part_at_some_time)
    BIND(IRI("http://schema.dia.mil/DefenseIntelligenceCoreOntology/hasOperationalStatus") AS ?operational_status)
  ## REMOVING HARDCODED GRAPH URI 20250225
  ## }
}
