PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cco: <http://www.ontologyrepository.com/CommonCoreOntologies/>
PREFIX dico: <http://schema.dia.mil/DefenseIntelligenceCoreOntology/>
PREFIX scmtemp: <http://blackcape.io/ontology/control-markings/>
PREFIX src: <http://blackcape.io/ontology/node#> 
PREFIX cnyobj: <http://blackcape.io/ontology/country_obj/>
PREFIX cnyid: <http://blackcape.io/ontology/country_id/>


CONSTRUCT {

    ?object_instance a dico:MilitaryOrganization ;
        dico:hasAllegianceTo ?cny.

    ?cny a cco:Country; 
        cco:described_by ?dice_cny_code ; 
        rdfs:label ?cny_label. 
    ## Country Code Identifier (FIPS10 code)
    ?dice_cny_code a dico:CountryCode; cco:has_text_value ?cny_cd.

    <http://blackcape.io/ontology/control-markings/AccessControlMarking> a owl:Class;
                               rdfs:subClassOf cco:DirectiveInformationContentEntity ,
                               src:acm_function_restriction ;
                               owl:isDefinedBy "https://www.dni.gov/files/documents/ICD/ICD-710.pdf"^^xsd:anyURI .

    src:acm_function_restriction a owl:Restriction;
                    owl:onProperty cco:prescribes;
                    owl:someValuesFrom src:IntelligenceDisseminationFunction .

    ?acm_instance a scmtemp:AccessControlMarking ; rdfs:label ?_derived_acm_guid.


}
WHERE
{
    ?r a src:Record; src:_id ?object_id.
    BIND(URI(CONCAT("http://blackcape.io/ontology/node#", ?object_id )) as ?object_instance)

    ?r src:_derived_acm_guid ?_derived_acm_guid.
    BIND(URI(CONCAT("http://blackcape.io/ontology/control-markings/", ?_derived_acm_guid )) as ?acm_instance)

    OPTIONAL {
        ?r src:_source_allegiance_fips10 ?_source_allegiance_fips10 .
        ?r src:_source_allegiance_gec ?_source_allegiance_gec .
        ?r src:_source_allegiance_iso2 ?_source_allegiance_iso2 .
        ?r src:_source_allegiance_iso3 ?_source_allegiance_iso3 .
        ?r src:_source_allegiance_isoNR ?_source_allegiance_isoNR .
        ?r src:_source_allegiance_original ?_source_allegiance_original .
        ?r src:_source_metadata_MIDB_Affiliation ?_source_metadata_MIDB_Affiliation .
        ?r src:_source_metadata_MIDB_Affiliation_translated ?_source_metadata_MIDB_Affiliation_translated .
        ?r src:_source_hierarchy_category ?_source_hierarchy_category .
        ?r src:_source_attributes_domain ?_source_attributes_domain .
    }
    OPTIONAL {
        ?r src:_source_acm_accms ?_source_acm_accms .
        ?r src:_source_acm_atom_energy ?_source_acm_atom_energy .
        ?r src:_source_acm_banner ?_source_acm_banner .
        ?r src:_source_acm_classif ?_source_acm_classif .
        ?r src:_source_acm_disp_only ?_source_acm_disp_only .
        ?r src:_source_acm_disponly_to ?_source_acm_disponly_to .
        ?r src:_source_acm_dissem_countries ?_source_acm_dissem_countries .
        ?r src:_source_acm_dissem_ctrls ?_source_acm_dissem_ctrls .
        ?r src:_source_acm_f_accms ?_source_acm_f_accms .
        ?r src:_source_acm_f_atom_energy ?_source_acm_f_atom_energy .
        ?r src:_source_acm_f_clearance ?_source_acm_f_clearance .
        ?r src:_source_acm_f_macs ?_source_acm_f_macs .
        ?r src:_source_acm_f_missions ?_source_acm_f_missions .
        ?r src:_source_acm_f_oc_org ?_source_acm_f_oc_org .
        ?r src:_source_acm_f_regions ?_source_acm_f_regions .
        ?r src:_source_acm_f_sar_id ?_source_acm_f_sar_id .
        ?r src:_source_acm_f_sci_ctrls ?_source_acm_f_sci_ctrls .
        ?r src:_source_acm_f_share ?_source_acm_f_share .
        ?r src:_source_acm_fgi_open ?_source_acm_fgi_open .
        ?r src:_source_acm_fgi_protect ?_source_acm_fgi_protect .
        ?r src:_source_acm_macs ?_source_acm_macs .
        ?r src:_source_acm_non_ic ?_source_acm_non_ic .
        ?r src:_source_acm_owner_prod ?_source_acm_owner_prod .
        ?r src:_source_acm_portion ?_source_acm_portion .
        ?r src:_source_acm_rel_to ?_source_acm_rel_to .
        ?r src:_source_acm_sar_id ?_source_acm_sar_id .
        ?r src:_source_acm_sci_ctrls ?_source_acm_sci_ctrls .
        ?r src:_source_acm_version ?_source_acm_version .

    }
    # Allegiance
    OPTIONAL {
        # capture
        ?r src:_source_allegiance_fips10 ?_source_allegiance_fips10 .
        ?r src:_source_allegiance_fullName ?_source_allegiance_fullName .

        # bind
        bind(strdt(?_source_allegiance_fips10 , xsd:string) as ?cny_cd)
        bind (URI(concat("http://blackcape.io/ontology/country_id/",?cny_cd)) as ?dice_cny_code)
        ## bind (URI(concat("http://blackcape.io/ontology/country_temp/",?_source_allegiance_fullName)) as ?cny)
        bind (STRDT(concat("Country of ",?_source_allegiance_fullName), xsd:string) as ?cny_label)

        bind (URI(concat("http://blackcape.io/ontology/country_obj/",?_source_allegiance_fullName)) as ?cny)
    }
    ## operating status
    OPTIONAL {
        ?r src:_source_metadata_MIDB_OperStatus ?_source_metadata_MIDB_OperStatus.
    }
}