import logging
from abc import ABC, abstractmethod
from typing import List, Optional

from oms_sdk.generated.generated_graphql_client import (
    AttributeQuery,
    ObservationObservation,
    RelationshipNodeQuery,
    RelationshipQuery,
)

from oms_sensemaking.config import SETTINGS
from oms_sensemaking.core.oms_crud import OmsCrudTool

LOGGER = logging.getLogger(__name__)


class GetGarrisonData(ABC):
    def __init__(self, oms_crud_tool: OmsCrudTool) -> None:
        self.oms_crud_tool = oms_crud_tool

    @abstractmethod
    def get_all_garrison_data(self, obs: ObservationObservation):
        raise NotImplementedError


class GetGarrisonDataAllAtOnce(GetGarrisonData):
    def get_all_garrison_data(self, obs: ObservationObservation):
        garrison_coords_lon_lat = self._fetch_garrison_coords(obs.nodeId)

        if garrison_coords_lon_lat:
            object_coords = obs.geometry["coordinates"]
            object_lat_lon = [object_coords[1], object_coords[0]]

            # first index is latitude, second is longitude
            garrison_lat_lon = [garrison_coords_lon_lat[1], garrison_coords_lon_lat[0]]

            return object_lat_lon, garrison_lat_lon

    def _fetch_garrison_coords(self, obs_node_id: str) -> Optional[List[float]]:
        """
        Return [lon, lat] for the home base of the observed node, or None.
        Uses a single named custom operation generated by ariadne-codegen (via the Python SDK).
        :param obs_node_id: Observation's nodeId
        """
        result = self.oms_crud_tool.oms_client.in_out_garrison_with_geo(
            id=obs_node_id,
            garrisonIris=[SETTINGS.inference_garrisoned_in_iri],
            geoIris=[SETTINGS.inference_geo_attribute_iri],
        )

        end_node = result.relationships.data[0].endNode if result.relationships and result.relationships.data else None

        attribute_data = (
            end_node.attributes.data[0]
            if end_node and hasattr(end_node, "attributes") and end_node.attributes.data
            else None
        )

        coords = (
            attribute_data.geometry["coordinates"]
            if attribute_data and isinstance(attribute_data.geometry, dict) and "coordinates" in attribute_data.geometry
            else None
        )
        return coords if isinstance(coords, list) and len(coords) >= 2 else None


class GetGarrisonDataSequential(GetGarrisonData):
    def get_all_garrison_data(self, obs: ObservationObservation):
        geo = obs.geometry
        # Find garrison node id through garrison relationship
        garrison_relationship_query = RelationshipQuery(
            objectPropertyIris=[SETTINGS.inference_garrisoned_in_iri],
            nodes=RelationshipNodeQuery(startNodeIds=[obs.nodeId]),
        )
        garrison_relationship_res = self.oms_crud_tool.get_relationships(garrison_relationship_query)

        if len(garrison_relationship_res.data):
            relationship = garrison_relationship_res.data[0]
            garrison_object_id = relationship.endNodeId

            # Find garrison coordinates through location attribute
            garrison_attribute_query = AttributeQuery(
                nodeIds=[garrison_object_id], attributeIris=[SETTINGS.inference_geo_attribute_iri]
            )
            garrison_attribute_res = self.oms_crud_tool.get_attributes(garrison_attribute_query)
            if len(garrison_attribute_res.data):
                garrison_object_coordinates = garrison_attribute_res.data[0].geometry["coordinates"]

                # Determine if object is in garrison
                object_coordinates = geo["coordinates"]
                object_coordinates = [object_coordinates[1], object_coordinates[0]]
                garrison_object_coordinates = [garrison_object_coordinates[1], garrison_object_coordinates[0]]

                return object_coordinates, garrison_object_coordinates


class GetGarrisonDataRetrieverFactory:
    def __init__(self, oms_crud_tool: OmsCrudTool):
        self.oms_crud_tool = oms_crud_tool

    def get_garrison_data_retriever(self, retriver_type: str):
        match retriver_type:
            case "Sequential":
                return GetGarrisonDataSequential(self.oms_crud_tool)
            case "AllAtOnce":
                return GetGarrisonDataAllAtOnce(self.oms_crud_tool)
            case _:
                raise ValueError("Invalid Garrison Data Retriever")
