"""Added new nodes table.

Revision ID: 20249161345
Revises: 202408191759
Create Date: 2024-09-16 13:48:19.701486

"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import oms_sensemaking


# revision identifiers, used by Alembic.
revision: str = '20249161345'
down_revision: Union[str, None] = '202408191759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nodes",
        sa.Column("id", sa.UUID(), nullable=False, comment="The ID of the node associated with this point."),
        sa.Column(
            "version", sa.String(), nullable=False, comment="The version of the node associated with this point."
        ),
        sa.Column(
            "acm", sa.String(), nullable=False, comment="The version of the node associated with this point."
        ),
        sa.Column(
            "tags", sa.ARRAY(sa.String()), nullable=False, comment="The version of the node associated with this point."
        ),
        sa.Column(
            "guideID", sa.String(), nullable=False, comment="The version of the node associated with this point."
        ),
        sa.Column(
            "name", sa.String(), nullable=False, comment="The version of the node associated with this point."
        ),
        sa.Column(
            "tier", sa.String(), nullable=False, comment="The version of the node associated with this point."
        ),
        sa.Column(
            "classIri", sa.String(), nullable=False, comment="The version of the node associated with this point."
        ),
        sa.Column(
            "className", sa.String(), nullable=False, comment="The version of the node associated with this point."
        ),
        sa.Column(
            "ifcCodes", sa.ARRAY(sa.String()), nullable=False, comment="The version of the node associated with this point."
        ),
        sa.Column(
            "allegience", sa.String(), nullable=False, comment="The version of the node associated with this point."
        ),
        sa.Column(
            "allegienceAor", sa.String(), nullable=False, comment="The version of the node associated with this point."
        ),
        sa.Column(
            "currentAor", sa.String(), nullable=False, comment="The version of the node associated with this point."
        ),
        sa.Column(
            "isNso", sa.Boolean(), nullable=False, comment="The version of the node associated with this point."
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nodes")),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nodes")
    # ### end Alembic commands ###
