"""Add observation mixin

Revision ID: 202412181131
Revises: 202410031446
Create Date: 2024-12-18 11:31:02.103122

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "202412181131"
down_revision: Union[str, None] = "202410031446"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "points",
        sa.Column("track_id", sa.UUID(), nullable=False, comment="The ID of the track associated with the object."),
    )
    op.add_column(
        "points",
        sa.Column(
            "observation_id", sa.UUID(), nullable=False, comment="The ID of the observation associated with the object."
        ),
    )
    op.add_column(
        "points",
        sa.Column(
            "observation_version",
            sa.Integer(),
            nullable=False,
            comment="The version of the observation associated with the object.",
        ),
    )
    op.drop_column("points", "attribute_id")
    op.drop_column("points", "attribute_version")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "points",
        sa.Column(
            "attribute_version",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True, # TODO: This is a temp solution to avoid NotNullViolation
            comment="The version of the attribute associated with the object.",
        ),
    )
    op.add_column(
        "points",
        sa.Column(
            "attribute_id",
            sa.UUID(),
            autoincrement=False,
            nullable=True, # TODO: This is a temp solution to avoid NotNullViolation
            comment="The ID of the attribute associated with the object.",
        ),
    )
    op.drop_column("points", "observation_version")
    op.drop_column("points", "observation_id")
    op.drop_column("points", "track_id")
    # ### end Alembic commands ###
