"""Added "findings" table.

Revision ID: 202409181707
Revises: 202408191759
Create Date: 2024-09-18 17:07:52.197324

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import oms_sensemaking
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "202409181707"
down_revision: Union[str, None] = "202408191759"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "findings",
        sa.Column("finding_id", sa.UUID(), nullable=False, comment="A unique identifier for the finding."),
        sa.Column(
            "finding_type",
            sa.Enum(
                "UNKNOWN",
                "GEO_COTRAVEL",
                "GEO_LOITER",
                "GEO_SIMILAR_TRACKS",
                "NLP_RECOGNIZED_ENTITY",
                name="findingtype",
            ),
            nullable=False,
            comment="The type of finding being represented.",
        ),
        sa.Column(
            "finding_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="The results of running a sensemaker.",
        ),
        sa.Column(
            "oms_version", sa.String(), nullable=True, comment="The version of OMS that the finding was published to."
        ),
        sa.Column(
            "published_at",
            oms_sensemaking.models.base.UtcDateTime(),
            nullable=True,
            comment="The time the finding was published.",
        ),
        sa.Column(
            "algorithm_name",
            sa.String(),
            nullable=False,
            comment="The name of the sensemaker that produced the finding.",
        ),
        sa.Column("algorithm_version", sa.String(), nullable=False, comment="The version of the sensemaker."),
        sa.Column(
            "algorithm_configuration",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="The configuration that the algorithm was run with.",
        ),
        sa.Column(
            "executed_at",
            oms_sensemaking.models.base.UtcDateTime(),
            nullable=False,
            comment="The time the algorithm was executed.",
        ),
        sa.Column(
            "acm",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="The ACM representing the classification of the data.",
        ),
        sa.Column(
            "created_at",
            oms_sensemaking.models.base.UtcDateTime(),
            nullable=False,
            comment="The time the record was created in the database.",
        ),
        sa.Column(
            "updated_at",
            oms_sensemaking.models.base.UtcDateTime(),
            nullable=False,
            comment="The time the record was last updated.",
        ),
        sa.PrimaryKeyConstraint("finding_id", name=op.f("pk_findings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("findings")
    sa.Enum(name='findingtype').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
