"""Added points table.

Revision ID: 202408191759
Revises:
Create Date: 2024-08-19 17:59:40.366069

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import oms_sensemaking

# revision identifiers, used by Alembic.
revision: str = "202408191759"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "points",
        sa.Column("node_id", sa.UUID(), nullable=False, comment="The ID of the node associated with the object."),
        sa.Column(
            "node_version", sa.Integer(), nullable=False, comment="The version of the node associated with this object."
        ),
        sa.Column(
            "attribute_id", sa.UUID(), nullable=False, comment="The ID of the attribute associated with the object."
        ),
        sa.Column(
            "attribute_version",
            sa.Integer(),
            nullable=False,
            comment="The version of the attribute associated with the object.",
        ),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
            comment="The 2D location of the point.",
        ),
        sa.Column("altitude", sa.Float(), nullable=True, comment="The altitude of the point."),
        sa.Column(
            "detection_time",
            oms_sensemaking.models.base.UtcDateTime(),
            nullable=False,
            comment="The time the point was detected.",
        ),
        sa.Column(
            "acm",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="The ACM representing the classification of the data.",
        ),
        sa.Column(
            "created_at",
            oms_sensemaking.models.base.UtcDateTime(),
            nullable=False,
            comment="The time the record was created in the database.",
        ),
        sa.Column(
            "updated_at",
            oms_sensemaking.models.base.UtcDateTime(),
            nullable=False,
            comment="The time the record was last updated.",
        ),
        sa.PrimaryKeyConstraint("node_id", "attribute_id", name=op.f("pk_points")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("points")
    # ### end Alembic commands ###
