"""Added points table.

Revision ID: 202408151416
Revises:
Create Date: 2024-08-15 14:16:31.347730

"""

from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa

import oms_sensemaking
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "202408151416"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "points",
        sa.Column("point_id", sa.UUID(), nullable=False, comment="Unique identifier."),
        sa.Column("node_id", sa.UUID(), nullable=False, comment="The ID of the node associated with this point."),
        sa.Column(
            "node_version", sa.Integer(), nullable=False, comment="The version of the node associated with this point."
        ),
        sa.Column(
            "attribute_id", sa.UUID(), nullable=False, comment="The ID of the attribute associated with this point."
        ),
        sa.Column(
            "attribute_version",
            sa.Integer(),
            nullable=False,
            comment="The version of the attribute associated with this point.",
        ),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
            comment="The 2D location of the point.",
        ),
        sa.Column("altitude", sa.Float(), nullable=True, comment="The altitude of the point."),
        sa.Column("geohash", sa.String(), nullable=False, comment="A geocoded representation of the location."),
        sa.Column(
            "detection_time",
            oms_sensemaking.models.base.UtcDateTime(),
            nullable=False,
            comment="The time the point was detected.",
        ),
        sa.Column(
            "acm",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="The ACM representing the classification of the Point.",
        ),
        sa.Column(
            "created_at",
            oms_sensemaking.models.base.UtcDateTime(),
            nullable=False,
            comment="The time the record was created in the database.",
        ),
        sa.Column(
            "updated_at",
            oms_sensemaking.models.base.UtcDateTime(),
            nullable=False,
            comment="The time the record was last updated.",
        ),
        sa.PrimaryKeyConstraint("point_id", name=op.f("pk_points")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("points")
    # ### end Alembic commands ###
