"""Added nodes table.

Revision ID: 202409271436
Revises: 202409181707
Create Date: 2024-09-27 14:36:29.357596

"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import oms_sensemaking
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '202409271436'
down_revision: Union[str, None] = '202409181707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.UUID(), nullable=False, comment='The ID of the node associated with the object.'),
    sa.Column('version', sa.Integer(), nullable=False, comment='The version of the node associated with this object.'),
    sa.Column('acm', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='The acm of the node.'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='A tags of the node.'),
    sa.Column('guideID', sa.String(), nullable=False, comment='The guideID of the node.'),
    sa.Column('name', sa.String(), nullable=False, comment='The name of the node.'),
    sa.Column('tier', sa.Enum('PRIMARY', 'DERIVATIVE', 'OBSERVATIONAL', name='objecttier'), nullable=False, comment='The tier of the node.'),
    sa.Column('classIri', sa.String(), nullable=False, comment='The classIri of the node.'),
    sa.Column('className', sa.String(), nullable=False, comment='The className of the node.'),
    sa.Column('ifcCodes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='The ifcCodes of the node.'),
    sa.Column('allegiance', sa.String(), nullable=False, comment='The allegiance of the node.'),
    sa.Column('allegianceAor', sa.String(), nullable=False, comment='The allegianceAor of the node.'),
    sa.Column('currentAor', sa.String(), nullable=False, comment='The currentAor of the node.'),
    sa.Column('isNso', sa.Boolean(), nullable=False, comment='The isNso of the node (boolean).'),
    sa.Column('created_at', oms_sensemaking.models.base.UtcDateTime(), nullable=False, comment='The time the record was created in the database.'),
    sa.Column('updated_at', oms_sensemaking.models.base.UtcDateTime(), nullable=False, comment='The time the record was last updated.'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nodes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nodes')
    # ### end Alembic commands ###
