"""Added nodes table.

Revision ID: 2024913159
Revises: 202408191759
Create Date: 2024-09-13 15:09:44.654418

"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import oms_sensemaking
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2024913159'
down_revision: Union[str, None] = '202408191759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('points', 'node_id',
               existing_type=sa.UUID(),
               comment='The ID of the node associated with the object.',
               existing_comment='The ID of the node associated with this point.',
               existing_nullable=False)
    op.alter_column('points', 'node_version',
               existing_type=sa.INTEGER(),
               comment='The version of the node associated with this object.',
               existing_comment='The version of the node associated with this point.',
               existing_nullable=False)
    op.alter_column('points', 'attribute_id',
               existing_type=sa.UUID(),
               comment='The ID of the attribute associated with the object.',
               existing_comment='The ID of the attribute associated with this point.',
               existing_nullable=False)
    op.alter_column('points', 'attribute_version',
               existing_type=sa.INTEGER(),
               comment='The version of the attribute associated with the object.',
               existing_comment='The version of the attribute associated with this point.',
               existing_nullable=False)
    op.alter_column('points', 'acm',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='The ACM representing the classification of the data.',
               existing_comment='The ACM representing the classification of the Point.',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('points', 'acm',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='The ACM representing the classification of the Point.',
               existing_comment='The ACM representing the classification of the data.',
               existing_nullable=False)
    op.alter_column('points', 'attribute_version',
               existing_type=sa.INTEGER(),
               comment='The version of the attribute associated with this point.',
               existing_comment='The version of the attribute associated with the object.',
               existing_nullable=False)
    op.alter_column('points', 'attribute_id',
               existing_type=sa.UUID(),
               comment='The ID of the attribute associated with this point.',
               existing_comment='The ID of the attribute associated with the object.',
               existing_nullable=False)
    op.alter_column('points', 'node_version',
               existing_type=sa.INTEGER(),
               comment='The version of the node associated with this point.',
               existing_comment='The version of the node associated with this object.',
               existing_nullable=False)
    op.alter_column('points', 'node_id',
               existing_type=sa.UUID(),
               comment='The ID of the node associated with this point.',
               existing_comment='The ID of the node associated with the object.',
               existing_nullable=False)
    # ### end Alembic commands ###
