"""Added source_id to Point table.

Revision ID: 202410031446
Revises: 202410011516
Create Date: 2024-10-03 14:46:58.837902

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "202410031446"
down_revision: Union[str, None] = "202410011516"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "points",
        sa.Column("source_id", sa.UUID(), nullable=False, comment="The ID of the source associated with the object."),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("points", "source_id")
    # ### end Alembic commands ###
