"""Added LogRecord table.

Revision ID: 202507011818
Revises: 202507011740
Create Date: 2025-06-09 11:40:52.794843

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import oms_sensemaking

# revision identifiers, used by Alembic.
revision: str = "202507011818"
down_revision: Union[str, None] = "202507011740"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "log_record",
        sa.Column("log_id", sa.UUID(), nullable=False, comment="The unique ID of the Log."),
        sa.Column(
            "timestamp", oms_sensemaking.models.base.UtcDateTime(), nullable=False, comment="The time the log occurred."
        ),
        sa.Column(
            "level",
            sa.Enum("DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL", name="loglevel"),
            nullable=False,
            comment="Log Record Level",
        ),
        sa.Column("module_name", sa.String(), nullable=False, comment="Name of the producing thread"),
        sa.Column("message", sa.TEXT(), nullable=False, comment="Log message"),
        sa.Column("exc_text", sa.TEXT(), nullable=True, comment="Exception text"),
        sa.Column(
            "acm",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="The ACM representing the classification of the data.",
        ),
        sa.Column(
            "created_at",
            oms_sensemaking.models.base.UtcDateTime(),
            nullable=False,
            comment="The time the record was created in the database.",
        ),
        sa.PrimaryKeyConstraint("log_id", name=op.f("pk_log_record")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("log_record")
    sa.Enum("DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL", name="loglevel").drop(op.get_bind())
    # ### end Alembic commands ###
