"""Updated points.point_id and tracks.track_id comments

Revision ID: 202506021502
Revises: 202504171216
Create Date: 2025-06-02 15:02:02.466485

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "202506021502"
down_revision: Union[str, None] = "202504171216"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # TODO why is this migration being made?????
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column(
    #     "points",
    #     "point_id",
    #     existing_type=sa.INTEGER(),
    #     comment="The unique ID of the Sensemaking Point.",
    #     existing_nullable=False,
    #     autoincrement=True,
    # )
    # op.drop_constraint("points_point_id_key", "points", type_="unique")
    # op.alter_column(
    #     "tracks",
    #     "track_id",
    #     existing_type=sa.INTEGER(),
    #     comment="The unique ID of the Track within the database only.",
    #     existing_comment="The unique ID of the Sensemaking Track.",
    #     existing_nullable=False,
    #     autoincrement=True,
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column(
    #     "tracks",
    #     "track_id",
    #     existing_type=sa.INTEGER(),
    #     comment="The unique ID of the Sensemaking Track.",
    #     existing_comment="The unique ID of the Track within the database only.",
    #     existing_nullable=False,
    #     autoincrement=True,
    # )
    # op.create_unique_constraint("points_point_id_key", "points", ["point_id"])
    # op.alter_column(
    #     "points",
    #     "point_id",
    #     existing_type=sa.INTEGER(),
    #     comment=None,
    #     existing_comment="The unique ID of the Sensemaking Point.",
    #     existing_nullable=False,
    #     autoincrement=True,
    # )
    # ### end Alembic commands ###
