"""Added weight column to points table.

Revision ID: 202502101854
Revises: 202502092036
Create Date: 2025-02-10 18:54:40.316232

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "202502101854"
down_revision: Union[str, None] = "202502092036"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "points",
        sa.Column(
            "weight",
            sa.Float(),
            nullable=False,
            comment="The weight assigned to the Point from confidence and other factors.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("points", "weight")
    # ### end Alembic commands ###
