"""Added provider to tracks

Revision ID: 202511041610
Revises: 202510301521
Create Date: 2025-11-04 16:10:00.0000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "202511041610"
down_revision: Union[str, None] = "202510301521"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tracks",
        sa.Column(
            "provider_id",
            sa.String(),
            nullable=False,
            comment="The provider ID representing the provider of the observations of the track",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracks", "provider_id")
    # ### end Alembic commands ###
