"""Added observation_confidence to mixin

Revision ID: 202502092036
Revises: 202501101242
Create Date: 2025-02-09 20:36:48.884542

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "202502092036"
down_revision: str | None = "202501271106"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "points",
        sa.Column(
            "observation_confidence",
            sa.String(),
            nullable=True,
            comment="The confidence level of the observation associated with the object.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("points", "observation_confidence")
    # ### end Alembic commands ###
