"""Added new Mil Symbol Finding Type.

Revision ID: 202501271106
Revises: 202501101242
Create Date: 2025-01-27 11:06:23.578186

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '202501271106'
down_revision: Union[str, None] = '202501101708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# source https://stackoverflow.com/questions/14845203/altering-an-enum-field-using-alembic
old_options = ("UNKNOWN",
                "GEO_COTRAVEL",
                "GEO_LOITER",
                "GEO_SIMILAR_TRACKS",
                "NLP_RECOGNIZED_ENTITY",
                "NLP_FINDINGS",
                "RESOLUTION_DUPLICATE",
                "INF_HAS_NAME",
                "INF_OUT_OF_GARRISON",
                "INF_INCURSION"
                )
new_options = sorted(old_options + ("MIL_SYMBOL_UPDATE",))

old_type = sa.Enum(*old_options, name='findingtype')
new_type = sa.Enum(*new_options, name='findingtype')
tmp_type = sa.Enum(*new_options, name='_findingtype')

tcr = sa.sql.table("findings",
                   sa.Column("finding_type", new_type, nullable=False))


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create a temporary "_findingtype" type, convert and drop the "old" type
    tmp_type.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE findings ALTER COLUMN finding_type TYPE _findingtype'
               ' USING finding_type::text::_findingtype')
    old_type.drop(op.get_bind(), checkfirst=False)
    # Create and convert to the "new" findingtype type
    new_type.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE findings ALTER COLUMN finding_type TYPE findingtype'
               ' USING finding_type::text::findingtype')
    tmp_type.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Convert MIL_SYMBOL_UPDATE findingtype into UNKNOWN
    op.execute(tcr.update().where(tcr.c.finding_type==u"MIL_SYMBOL_UPDATE")
               .values(finding_type="UNKNOWN"))
    # Create a temporary "_findingtype" type, convert and drop the "new" type
    tmp_type.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE findings ALTER COLUMN finding_type TYPE _findingtype'
               ' USING finding_type::text::_findingtype')
    new_type.drop(op.get_bind(), checkfirst=False)
    # Create and convert to the "old" findingtype type
    old_type.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE findings ALTER COLUMN finding_type TYPE findingtype'
               ' USING finding_type::text::findingtype')
    tmp_type.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
