"""Points table uniqueness

Revision ID: 202507011740
Revises: 202506161854
Create Date: 2025-06-06 18:40:27.859394

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "202507011740"
down_revision: Union[str, None] = "202506161854"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "points",
        "point_id",
        existing_type=sa.INTEGER(),
        comment="The unique ID of the Sensemaking Point.",
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('points_point_id_seq'::regclass)"),
    )
    op.drop_constraint("fk_track_points_point_id_points", "track_points", type_="foreignkey")
    op.drop_constraint("points_point_id_key", "points", type_="unique")
    op.create_foreign_key(
        constraint_name="fk_track_points_point_id_points",
        source_table="track_points",
        referent_table="points",
        local_cols=["point_id"],
        remote_cols=["point_id"]
    )
    op.alter_column(
        "tracks",
        "track_id",
        existing_type=sa.INTEGER(),
        comment="The unique ID of the Track within the database only.",
        existing_comment="The unique ID of the Sensemaking Track.",
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tracks",
        "track_id",
        existing_type=sa.INTEGER(),
        comment="The unique ID of the Sensemaking Track.",
        existing_comment="The unique ID of the Track within the database only.",
        existing_nullable=False,
        autoincrement=True,
    )
    op.create_unique_constraint("points_point_id_key", "points", ["point_id"])
    op.alter_column(
        "points",
        "point_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="The unique ID of the Sensemaking Point.",
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('points_point_id_seq'::regclass)"),
    )
    # ### end Alembic commands ###
