"""Remove semantic table.

Revision ID: 202506161854
Revises: 202504171216
Create Date: 2025-06-16 18:54:04.837834

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import oms_sensemaking

# revision identifiers, used by Alembic.
revision: str = "202506161854"
down_revision: Union[str, None] = "202504171216"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nodes")
    sa.Enum(name="objecttier").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nodes",
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (primary key)"),
        sa.Column("version", sa.Integer(), nullable=False, comment="version"),
        sa.Column("acm", postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="acm"),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="tags"),
        sa.Column("guide_id", sa.String(), nullable=False, comment="guideID"),
        sa.Column("name", sa.String(), nullable=False, comment="name"),
        sa.Column(
            "tier", sa.Enum("PRIMARY", "DERIVATIVE", "OBSERVATIONAL", name="objecttier"), nullable=False, comment="tier"
        ),
        sa.Column("class_iri", sa.String(), nullable=False, comment="classIri"),
        sa.Column("class_name", sa.String(), nullable=False, comment="className"),
        sa.Column("ifc_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="ifcCodes"),
        sa.Column("allegiance", sa.String(), nullable=False, comment="allegiance"),
        sa.Column("allegiance_aor", sa.String(), nullable=False, comment="allegianceAor"),
        sa.Column("current_aor", sa.String(), nullable=False, comment="currentAor"),
        sa.Column("is_nso", sa.Boolean(), nullable=False, comment="isNso (boolean)"),
        sa.Column(
            "created_at",
            oms_sensemaking.models.base.UtcDateTime(),
            nullable=False,
            comment="The time the record was created in the database.",
        ),
        sa.Column(
            "updated_at",
            oms_sensemaking.models.base.UtcDateTime(),
            nullable=False,
            comment="The time the record was last updated.",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nodes")),
    )
    # ### end Alembic commands ###
