"""Added acm to tracks

Revision ID: 202504171216
Revises: 202502171426
Create Date: 2025-04-17 12:16:26.418846

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "202504171216"
down_revision: Union[str, None] = "202502171426"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tracks",
        sa.Column(
            "acm",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="The ACM representing the classification of the data.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracks", "acm")
    # ### end Alembic commands ###
