"""Added tracks and track_points tables.

Revision ID: 202502171426
Revises: 202502101854
Create Date: 2025-02-17 14:27:00.437609

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "202502171426"
down_revision: Union[str, None] = "202502101854"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tracks",
        sa.Column(
            "node_id", sa.UUID(), nullable=False, comment="The node ID of the object associated with this track."
        ),
        sa.Column(
            "algorithm", sa.String(), nullable=True, comment="The track weaver algorithm used to create this track."
        ),
        sa.Column(
            "track_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="The unique ID of the Sensemaking Track.",
        ),
        sa.Column(
            "observation_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="The list of any observation IDs used to create this track, even if dropped.",
        ),
        sa.Column("track_uuid", sa.UUID(), nullable=False, comment="The UUID of the track within Sensemaker."),
        sa.PrimaryKeyConstraint("track_id", name=op.f("pk_tracks")),
    )
    op.execute("ALTER TABLE points ADD point_id SERIAL UNIQUE NOT NULL")
    op.create_primary_key("pk_points", "points", ["point_id"])
    op.drop_column("points", "track_id")
    op.create_table(
        "track_points",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("point_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["point_id"], ["points.point_id"], name=op.f("fk_track_points_point_id_points")),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.track_id"], name=op.f("fk_track_points_track_id_tracks")),
        sa.PrimaryKeyConstraint("track_id", "point_id", name=op.f("pk_track_points")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "points",
        sa.Column(
            "track_id",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
            comment="The ID of the track associated with the object.",
        ),
    )
    op.drop_table("track_points")
    op.drop_table("tracks")
    op.drop_constraint("point_id", "points")
    op.drop_column("points", "point_id")
    # ### end Alembic commands ###
