"""Added AuditLogError Table.

Revision ID: 202507092319
Revises: 202507011740
Create Date: 2025-07-09 23:19:02.354369

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import oms_sensemaking

# revision identifiers, used by Alembic.
revision: str = "202507092319"
down_revision: Union[str, None] = "202507011740"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log_error",
        sa.Column("id", sa.UUID(), nullable=False, comment="The unique ID of the Log."),
        sa.Column("object_id", sa.UUID(), nullable=False, comment="The unique id of the object in OMS."),
        sa.Column(
            "object_type",
            sa.Enum(
                "ORIGINATOR",
                "PROVIDER",
                "SOURCE",
                "ATTRIBUTE",
                "OBSERVATION",
                "ACTIVITY",
                "RELATIONSHIP",
                "NODE",
                "COMMENT",
                "ALERT",
                "OBJECT_LIST",
                "USER_PREFERENCES",
                "BASEBALL_CARD",
                name="objecttype",
            ),
            nullable=False,
            comment="The type of object that the event was triggered on.",
        ),
        sa.Column(
            "event_type",
            sa.Enum("CREATE", "UPDATE", "DELETE", "RESTORE", "VERIFY", "MERGE_SOURCE", "MERGE_TARGET", name="action"),
            nullable=False,
            comment="They type of event (e.g. create, update, or delete).",
        ),
        sa.Column("module_name", sa.String(), nullable=False, comment="Name of the producing thread"),
        sa.Column("message", sa.TEXT(), nullable=False, comment="Log message"),
        sa.Column("exc_text", sa.TEXT(), nullable=True, comment="Exception text"),
        sa.Column(
            "acm",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="The ACM representing the classification of the data.",
        ),
        sa.Column(
            "created_at",
            oms_sensemaking.models.base.UtcDateTime(),
            nullable=False,
            comment="The time the record was created in the database.",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log_error")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audit_log_error")
    sa.Enum(
        "ORIGINATOR",
        "PROVIDER",
        "SOURCE",
        "ATTRIBUTE",
        "OBSERVATION",
        "ACTIVITY",
        "RELATIONSHIP",
        "NODE",
        "COMMENT",
        "ALERT",
        "OBJECT_LIST",
        "USER_PREFERENCES",
        "BASEBALL_CARD",
        name="objecttype").drop(op.get_bind())
    sa.Enum(
        "CREATE",
        "UPDATE",
        "DELETE",
        "RESTORE",
        "VERIFY",
        "MERGE_SOURCE",
        "MERGE_TARGET",
        name="action").drop(op.get_bind())
    # ### end Alembic commands ###
