"""added index on points table

Revision ID: 202511112210
Revises: 202510301521
Create Date: 2025-11-11 22:10:32.170304

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "202511112210"
down_revision: Union[str, None] = "202510301521"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Composite index for fast lookups on equality filters
    op.create_index(
        "idx_points_lookup",
        "points",
        [
            "node_id",
            "observation_id",
            "observation_confidence",
            "source_id",
            "weight",
        ],
        unique=False,
    )

    # GiST spatial index for location geometry
    op.create_index(
        "idx_points_location",
        "points",
        ["location"],
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_points_location", table_name="points")
    op.drop_index("idx_points_lookup", table_name="points")
    # ### end Alembic commands ###
