"""Added settings table.

Revision ID: 202510301521
Revises: 202507151200
Create Date: 2025-10-30 15:21:37.032183

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "202510301521"
down_revision: Union[str, None] = "202507151200"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("setting_id", sa.Integer, nullable=False, primary_key=True, comment="The ID of the setting."),
        sa.Column("field_name", sa.String(), nullable=False, comment="The field name for the setting."),
        sa.Column(
            "field_value",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="The value of the field.",
        ),
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings")
    pass
    # ### end Alembic commands ###
