"""Updated column descriptions

Revision ID: 202601161555
Revises: 202512101040
Create Date: 2026-01-16 15:55:13.540016

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "202601161555"
down_revision: Union[str, None] = "202512101040"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audit_log_error",
        "object_id",
        existing_type=sa.UUID(),
        comment="The unique id of the object in ATOMS.",
        existing_comment="The unique id of the object in OMS.",
        existing_nullable=False,
    )
    op.alter_column(
        "findings",
        "oms_version",
        existing_type=sa.VARCHAR(),
        comment="The version of ATOMS that the finding was published to.",
        existing_comment="The version of OMS that the finding was published to.",
        existing_nullable=True,
    )
    op.alter_column(
        "tracks",
        "provider_id",
        existing_type=sa.VARCHAR(),
        type_=sa.UUID(),
        postgresql_using="provider_id::uuid",
        comment="The provider ID of the provider associated with this track.",
        existing_comment="The provider ID representing the provider of the observations of the track",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tracks",
        "provider_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(),
        postgresql_using="provider_id::varchar",
        comment="The provider ID representing the provider of the observations of the track",
        existing_comment="The provider ID of the provider associated with this track.",
        existing_nullable=False,
    )
    op.alter_column(
        "findings",
        "oms_version",
        existing_type=sa.VARCHAR(),
        comment="The version of OMS that the finding was published to.",
        existing_comment="The version of ATOMS that the finding was published to.",
        existing_nullable=True,
    )
    op.alter_column(
        "audit_log_error",
        "object_id",
        existing_type=sa.UUID(),
        comment="The unique id of the object in OMS.",
        existing_comment="The unique id of the object in ATOMS.",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
