"""Added aggressor port table.

Revision ID: 202604021132
Revises: 202603111218
Create Date: 2026-04-02 11:32:35.288413

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

import oms_sensemaking

# revision identifiers, used by Alembic.
revision: str = "202604021132"
down_revision: Union[str, None] = "202603111218"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade the database schema. The following are the set of columns
    we want to add to the data set that will exist in PostgreSQL
    """
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    op.create_table(
        "aggressor_ports",
        sa.Column("capco", sa.String(), nullable=False, comment="Classification for the node."),
        sa.Column("class_iri", sa.String(), nullable=False, comment="Iri for the node."),
        sa.Column("confidence", sa.String(), nullable=False, comment="Confidence in the observation."),
        sa.Column("node_id", sa.String(), nullable=False, comment="Unique ID for the node."),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
            comment="The 2D location of the point.",
        ),
        sa.Column(
            "start_time",
            oms_sensemaking.models.base.UtcDateTime(),
            nullable=False,
            comment="When port data was queried for, same as end_time as ports are static.",
        ),
        sa.Column(
            "end_time",
            oms_sensemaking.models.base.UtcDateTime(),
            nullable=False,
            comment="When port data was queried for, same as end_time as ports are static.",
        ),
    )
    op.create_index("idx_port_node_id", "aggressor_ports", ["node_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema. Drop the table and the field we use for indexing"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_port_node_id", table_name="aggressor_ports")
    op.drop_table("aggressor_ports")
    # ### end Alembic commands ###
