"""Remove provider id from tracks table

Revision ID: 202602161306
Revises: 202602020951
Create Date: 2026-02-16 13:06:43.982652

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "202602161306"
down_revision: Union[str, None] = "202602020951"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracks", "provider_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tracks",
        sa.Column(
            "provider_id",
            sa.UUID(),
            nullable=True,
            comment="The provider ID of the provider associated with this track.",
        ),
    )
    ## Need to add dummy UUID
    op.execute("UPDATE tracks SET provider_id = '00000000-0000-0000-0000-000000000000'")
    op.alter_column("tracks", "provider_id", nullable=False)
    # ### end Alembic commands ###
