"""Adding an index to audit log error created_at

Revision ID: 202603111218
Revises: 202603041348
Create Date: 2026-03-11 12:18:42.131094

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "202603111218"
down_revision: Union[str, None] = "202603041348"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_audit_log_error_created_at"), "audit_log_error", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_log_error_created_at"), table_name="audit_log_error")
    # ### end Alembic commands ###
