"""Add atoms_id and atoms_type to findings

Revision ID: 202602020951
Revises: 202601221025
Create Date: 2026-02-02 09:51:35.577756

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "202602020951"
down_revision: Union[str, None] = "202601221025"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    atoms_type_enum = sa.Enum("NODE", "ATTRIBUTE", "RELATIONSHIP", "ACTIVITY", "EVENTS", name="atomstype")
    atoms_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "findings",
        sa.Column(
            "atoms_id",
            sa.UUID(),
            nullable=True,
            comment="The atoms ID representing the data in atoms core.",
        ),
    )
    op.add_column(
        "findings",
        sa.Column("atoms_type", atoms_type_enum, nullable=True, comment="Type of the data the atoms ID represents."),
    )

    op.create_index(
        "ix_findings_lookup_composite", "findings", ["atoms_id", "finding_type", "atoms_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_findings_lookup_composite", table_name="findings")
    op.drop_column("findings", "atoms_type")
    op.drop_column("findings", "atoms_id")

    sa.Enum(name="atomstype").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
