"""Add COCOM table.

Revision ID: 202603271036
Revises: 202602161306
Create Date: 2026-03-27 10:36:15.138817

"""

from typing import Sequence, Union
from src.oms_sensemaking.config import SETTINGS

import geoalchemy2
import sqlalchemy as sa
from alembic import op

import oms_sensemaking

# revision identifiers, used by Alembic.
revision: str = "202603271036"
down_revision: Union[str, None] = "202603111218"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    op.create_table(
        "aggressor_ports",
        sa.Column("capco", sa.String(), nullable=False, comment="Classification for the node"),
        sa.Column("class_iri", sa.String(), nullable=False, comment="The iri of the port"),
        sa.Column("confidence", sa.String(), nullable=False, comment="How confident we are in this observation"),
        sa.Column("node_id", sa.UUID(), nullable=False, comment="Unique ID of the node associated with the object."),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=SETTINGS.srid,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
            comment="The 2D location of the point.",
        ),
        sa.Column(
            "start_time",
            oms_sensemaking.models.base.UtcDateTime(),
            nullable=False,
            comment="The time the point was queired for from WPI.",
        ),
        sa.Column(
            "end_time",
            oms_sensemaking.models.base.UtcDateTime(),
            nullable=False,
            comment="The time for when the point was extracted.",
        ),
    )
    op.create_index("idx_port_nodeId", "aggressor_ports", ["nodeId"], postgresql_using="gist")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_port_nodeId", table_name="aggressor_ports")
    op.drop_table("aggressor_ports")
    # ### end Alembic commands ###
