# A configuration file to define the available activity states
states:
  - UNKNOWN
  - ACTIVE
  - ANCHORED
  - ASCM_TRANSLOADING
  - AT_AIRFIELD
  - AWAITING_REPAIR
  - CONSTRUCTION_PRE_LAUNCH
  - COTRAVEL
  - COVERED
  - DECOMMISSIONED
  - DEPLOYED
  - DESTROYED
  - ENGAGING
  - EXERCISES
  - FITTING_OUT
  - FLANKING
  - FUEL_TRANSFER
  - GRAVING_DOCK_REPAIR_WAYS
  - INACTIVE
  - INCURSION
  - IN_FLIGHT
  - STATIONARY
  - IN_GARRISON
  - IN_PORT
  - UNDERWAY
  - IN_MAINTENANCE
  - IN_TUNNEL
  - INACTIVE
  - MOVED_TO_SHIPYARD
  - MUNITIONS_LOADING
  - MUSEUM_PIECE
  - MUSTERED_OUT
  - NO_REPORTABLE_ACTIVITY
  - OPERATIONS
  - OUT_OF_GARRISON
  - PATROLS
  - RECONNAISSANCE
  - SCRAPPED
  - SEA_TRIALS
  - SIGNIFICANT_ACTIVITY
  - STAGING
  - STATIONARY
  - SUNK
  - TRAINING
  - TRANSFERRED
  - UNDERGOING_DEPERM
  - UNDERWAY
  - UNIDENTIFIED_PIERSIDE_ACTIVITY
  - WEATHER_AVOIDANCE
  - WEAPONS_TESTING
