labels:
  - SM_ENRICHED
  - SM_CONNECTED_TRACK
  - SM_INFERENCED
  - SM_DATA
  - GEOSPATIAL_SM
  - COTRAVEL_SM
  - LOITER_SM
  - INFERENCE_SM
  - INCURSION_RULE
  - HAS_NAME_RULE
  - IN/OUT_GARRISON_RULE
  - MILITARY_SYMBOL_SM
  - RESOLUTION_SM
  - v1.0.0