empty_findings = {"ner_entities": [], "ner_relationships": [], "document_entity": None, "document_relationships": []}

large_findings = {
    "ner_entities": [
        {
            "type": "ORGANIZATION",
            "objectId": "EntityMention-1",
            "uuid": "8705ff40-e8a6-41e8-8f29-1afb3b712e74",
            "hstart": 0,
            "hend": 1,
            "estart": 0,
            "eend": 1,
            "headPosition": 0,
            "value": "EU",
            "corefID": -1,
        },
        {
            "type": "PEOPLE",
            "objectId": "EntityMention-4",
            "uuid": "3f8ee81b-91c8-42ea-b93a-e00b548b2341",
            "hstart": 1,
            "hend": 2,
            "estart": 0,
            "eend": 2,
            "headPosition": 1,
            "value": "Blackburn",
            "corefID": -1,
        },
        {
            "type": "ORGANIZATION",
            "objectId": "EntityMention-7",
            "uuid": "5bad8de8-6462-4d0c-b835-a91b496701cf",
            "hstart": 6,
            "hend": 7,
            "estart": 5,
            "eend": 7,
            "headPosition": 6,
            "value": "Commission",
            "corefID": -1,
        },
        {
            "type": "ORGANIZATION",
            "objectId": "EntityMention-14",
            "uuid": "4c3612ea-318e-4e7c-8c5d-5849f31a459b",
            "hstart": 6,
            "hend": 7,
            "estart": 5,
            "eend": 7,
            "headPosition": 6,
            "value": "Union",
            "corefID": -1,
        },
        {
            "type": "PEOPLE",
            "objectId": "EntityMention-15",
            "uuid": "964b4e09-0d35-4a8b-b729-4c2748ca6eba",
            "hstart": 11,
            "hend": 12,
            "estart": 10,
            "eend": 12,
            "headPosition": 11,
            "value": "Zwingmann",
            "corefID": -1,
        },
        {
            "type": "ORGANIZATION",
            "objectId": "EntityMention-18",
            "uuid": "da6c9771-80f2-416d-a75e-3c983f42e1ee",
            "hstart": 20,
            "hend": 21,
            "estart": 20,
            "eend": 21,
            "headPosition": 20,
            "value": "Commission",
            "corefID": -1,
        },
        {
            "type": "PEOPLE",
            "objectId": "EntityMention-20",
            "uuid": "5ff971fb-7c70-4980-bbe2-1943a3c033f1",
            "hstart": 27,
            "hend": 28,
            "estart": 24,
            "eend": 28,
            "headPosition": 27,
            "value": "Pas",
            "corefID": -1,
        },
        {
            "type": "ORGANIZATION",
            "objectId": "EntityMention-21",
            "uuid": "de03cbb7-e590-46a4-b876-8132df2cb6d6",
            "hstart": 23,
            "hend": 24,
            "estart": 22,
            "eend": 24,
            "headPosition": 23,
            "value": "Union",
            "corefID": -1,
        },
        {
            "type": "ORGANIZATION",
            "objectId": "EntityMention-23",
            "uuid": "1c50bf36-d9e5-4b86-9b3a-f07c55661986",
            "hstart": 7,
            "hend": 8,
            "estart": 7,
            "eend": 8,
            "headPosition": 7,
            "value": "EU",
            "corefID": -1,
        },
        {
            "type": "PEOPLE",
            "objectId": "EntityMention-24",
            "uuid": "4fd41c08-ebc2-44ff-bd6b-86ee5c0a5e65",
            "hstart": 11,
            "hend": 12,
            "estart": 10,
            "eend": 12,
            "headPosition": 11,
            "value": "Fischler",
            "corefID": -1,
        },
        {
            "type": "PEOPLE",
            "objectId": "EntityMention-25",
            "uuid": "c155665b-a654-40f9-ad7d-a2aaf03e6231",
            "hstart": 0,
            "hend": 1,
            "estart": 0,
            "eend": 1,
            "headPosition": 0,
            "value": "Fischler",
            "corefID": -1,
        },
        {
            "type": "PEOPLE",
            "objectId": "EntityMention-32",
            "uuid": "38da5ce2-f827-4475-93e4-979517c57d2f",
            "hstart": 1,
            "hend": 2,
            "estart": 1,
            "eend": 2,
            "headPosition": 1,
            "value": "Fischler",
            "corefID": -1,
        },
        {
            "type": "ORGANIZATION",
            "objectId": "EntityMention-33",
            "uuid": "c8469c6c-9139-457c-a862-8b1742102f84",
            "hstart": 9,
            "hend": 10,
            "estart": 9,
            "eend": 10,
            "headPosition": 9,
            "value": "EU",
            "corefID": -1,
        },
        {
            "type": "PEOPLE",
            "objectId": "EntityMention-36",
            "uuid": "967a3381-14ae-4124-8f70-756fdbcec53f",
            "hstart": 5,
            "hend": 6,
            "estart": 3,
            "eend": 6,
            "headPosition": 5,
            "value": "Palacio",
            "corefID": -1,
        },
        {
            "type": "PEOPLE",
            "objectId": "EntityMention-37",
            "uuid": "c3cc0e47-6390-4663-a88d-a396e7259958",
            "hstart": 9,
            "hend": 10,
            "estart": 9,
            "eend": 10,
            "headPosition": 9,
            "value": "Fischler",
            "corefID": -1,
        },
        {
            "type": "ORGANIZATION",
            "objectId": "EntityMention-38",
            "uuid": "8f2f984a-85cc-4ce5-92df-4d5d8cf2aab6",
            "hstart": 12,
            "hend": 13,
            "estart": 12,
            "eend": 13,
            "headPosition": 12,
            "value": "EU",
            "corefID": -1,
        },
        {
            "type": "PEOPLE",
            "objectId": "EntityMention-41",
            "uuid": "2ed9d9c4-20e9-4368-a615-6a34fe70a095",
            "hstart": 5,
            "hend": 6,
            "estart": 5,
            "eend": 6,
            "headPosition": 5,
            "value": "Fischler",
            "corefID": -1,
        },
        {
            "type": "ORGANIZATION",
            "objectId": "EntityMention-42",
            "uuid": "87832124-24bb-4655-9465-6dba28f35f70",
            "hstart": 1,
            "hend": 2,
            "estart": 1,
            "eend": 2,
            "headPosition": 1,
            "value": "EU",
            "corefID": -1,
        },
        {
            "type": "LOCATION",
            "objectId": "EntityMention-50",
            "uuid": "d8e96c44-dc3f-433d-abb2-b87ff9ca5ab3",
            "hstart": 33,
            "hend": 34,
            "estart": 33,
            "eend": 34,
            "headPosition": 33,
            "value": "Europe",
            "corefID": -1,
        },
        {
            "type": "ORGANIZATION",
            "objectId": "EntityMention-52",
            "uuid": "78790ae7-3334-4349-a868-f196f687fb42",
            "hstart": 26,
            "hend": 27,
            "estart": 22,
            "eend": 27,
            "headPosition": 26,
            "value": "Union",
            "corefID": -1,
        },
        {
            "type": "ORGANIZATION",
            "objectId": "EntityMention-53",
            "uuid": "068d51fd-830b-4e32-9bdc-5446367b29ed",
            "hstart": 28,
            "hend": 29,
            "estart": 28,
            "eend": 29,
            "headPosition": 28,
            "value": "NFU",
            "corefID": -1,
        },
        {
            "type": "PEOPLE",
            "objectId": "EntityMention-55",
            "uuid": "53677e74-3c98-4b02-a13b-b5cda310f693",
            "hstart": 33,
            "hend": 34,
            "estart": 31,
            "eend": 34,
            "headPosition": 33,
            "value": "Jones",
            "corefID": -1,
        },
        {
            "type": "ORGANIZATION",
            "objectId": "EntityMention-56",
            "uuid": "1d2f20d6-efa3-48de-a18d-4d6c84149780",
            "hstart": 37,
            "hend": 38,
            "estart": 36,
            "eend": 38,
            "headPosition": 37,
            "value": "radio",
            "corefID": -1,
        },
    ],
    "ner_relationships": [
        {
            "type": "Work_For",
            "objectId": "RelationMention-6",
            "uuid": "ea545e2d-872f-425a-a927-a12d2cfe78b2",
            "start": 7,
            "end": 12,
            "relations": [
                "Work_For, 0.3224715096589502",
                "_NR, 0.26246742279215124",
                "Live_In, 0.19653166775709885",
                "OrgBased_In, 0.18560269000979812",
                "Located_In, 0.03292670978200148",
            ],
            "entities": [
                {
                    "type": "ORGANIZATION",
                    "objectId": "EntityMention-23",
                    "uuid": "1c50bf36-d9e5-4b86-9b3a-f07c55661986",
                    "hstart": 7,
                    "hend": 8,
                    "estart": 7,
                    "eend": 8,
                    "headPosition": 7,
                    "value": "EU",
                    "corefID": -1,
                },
                {
                    "type": "PEOPLE",
                    "objectId": "EntityMention-24",
                    "uuid": "4fd41c08-ebc2-44ff-bd6b-86ee5c0a5e65",
                    "hstart": 11,
                    "hend": 12,
                    "estart": 10,
                    "eend": 12,
                    "headPosition": 11,
                    "value": "Fischler",
                    "corefID": -1,
                },
            ],
        }
    ],
    "document_entity": {
        "document_id": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
        "value": "EU rejects German call to boycott British lamb. Peter Blackburn BRUSSELS 1996-08-22 The European "
        "Commission said on Thursday it disagreed with German advice to consumers to shun British lamb until "
        "scientists determine whether mad cow disease can be transmitted to sheep. Germany's representative "
        "to the European Union's veterinary committee Werner Zwingmann said on Wednesday consumers should "
        "buy sheepmeat from countries other than Britain until the scientific advice was clearer. 'We don't "
        "support any such recommendation because we don't see any grounds for it,' the Commission's chief "
        "spokesman Nikolaus van der Pas told a news briefing. He said further scientific study was required "
        "and if it was found that action was needed it should be taken by the European Union. He said a "
        "proposal last month by EU Farm Commissioner Franz Fischler to ban sheep brains, spleens and spinal "
        "cords from the human and animal food chains was a highly specific and precautionary move to protect "
        "human health. Fischler proposed EU-wide measures after reports from Britain and France that under "
        "laboratory conditions sheep could contract Bovine Spongiform Encephalopathy (BSE) -- mad cow "
        "disease. But Fischler agreed to review his proposal after the EU's standing veterinary committee, "
        "mational animal health officials, questioned if such action was justified as there was only a "
        "slight risk to human health. Spanish Farm Minister Loyola de Palacio had earlier accused Fischler "
        "at an EU farm ministers' meeting of causing unjustified alarm through 'dangerous generalisation.'. "
        "Only France and Britain backed Fischler's proposal. The EU's scientific veterinary and "
        "multidisciplinary committees are due to re-examine the issue early next month and make "
        "recommendations to the senior veterinary officials. Sheep have long been known to contract scrapie, "
        "a brain-wasting disease similar to BSE which is believed to have been transferred to cattle through "
        "feed containing animal waste. British farmers denied on Thursday there was any danger to human "
        "health from their sheep, but expressed concern that German government advice to consumers to avoid "
        "British lamb might influence consumers across Europe. 'What we have to be extremely careful of is "
        "how other countries are going to take Germany's lead,' Welsh National Farmers' Union (NFU) chairman "
        "John Lloyd Jones said on BBC radio. Bonn has led efforts to protect public health after consumer "
        "confidence collapsed in March after a British report suggested humans could contract an illness "
        "similar to mad cow disease by eating contaminated beef. Germany imported 47,600 sheep from Britain "
        "last year, nearly half of total imports. It brought in 4,275 tonnes of British mutton, "
        "some 10 percent of overall imports.",
        "entity_type": "DOCUMENT",
    },
    "document_relationships": [
        {
            "doc_obj_id": "DocumentRelation-1",
            "document_uuid": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
            "entity_obj_id": "EntityMention-1",
            "entity_uuid": "8705ff40-e8a6-41e8-8f29-1afb3b712e74",
            "type": "Document_Contains_Entity",
        },
        {
            "doc_obj_id": "DocumentRelation-2",
            "document_uuid": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
            "entity_obj_id": "EntityMention-4",
            "entity_uuid": "3f8ee81b-91c8-42ea-b93a-e00b548b2341",
            "type": "Document_Contains_Entity",
        },
        {
            "doc_obj_id": "DocumentRelation-3",
            "document_uuid": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
            "entity_obj_id": "EntityMention-7",
            "entity_uuid": "5bad8de8-6462-4d0c-b835-a91b496701cf",
            "type": "Document_Contains_Entity",
        },
        {
            "doc_obj_id": "DocumentRelation-4",
            "document_uuid": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
            "entity_obj_id": "EntityMention-14",
            "entity_uuid": "4c3612ea-318e-4e7c-8c5d-5849f31a459b",
            "type": "Document_Contains_Entity",
        },
        {
            "doc_obj_id": "DocumentRelation-5",
            "document_uuid": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
            "entity_obj_id": "EntityMention-15",
            "entity_uuid": "964b4e09-0d35-4a8b-b729-4c2748ca6eba",
            "type": "Document_Contains_Entity",
        },
        {
            "doc_obj_id": "DocumentRelation-6",
            "document_uuid": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
            "entity_obj_id": "EntityMention-18",
            "entity_uuid": "da6c9771-80f2-416d-a75e-3c983f42e1ee",
            "type": "Document_Contains_Entity",
        },
        {
            "doc_obj_id": "DocumentRelation-7",
            "document_uuid": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
            "entity_obj_id": "EntityMention-20",
            "entity_uuid": "5ff971fb-7c70-4980-bbe2-1943a3c033f1",
            "type": "Document_Contains_Entity",
        },
        {
            "doc_obj_id": "DocumentRelation-8",
            "document_uuid": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
            "entity_obj_id": "EntityMention-21",
            "entity_uuid": "de03cbb7-e590-46a4-b876-8132df2cb6d6",
            "type": "Document_Contains_Entity",
        },
        {
            "doc_obj_id": "DocumentRelation-9",
            "document_uuid": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
            "entity_obj_id": "EntityMention-23",
            "entity_uuid": "1c50bf36-d9e5-4b86-9b3a-f07c55661986",
            "type": "Document_Contains_Entity",
        },
        {
            "doc_obj_id": "DocumentRelation-10",
            "document_uuid": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
            "entity_obj_id": "EntityMention-24",
            "entity_uuid": "4fd41c08-ebc2-44ff-bd6b-86ee5c0a5e65",
            "type": "Document_Contains_Entity",
        },
        {
            "doc_obj_id": "DocumentRelation-11",
            "document_uuid": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
            "entity_obj_id": "EntityMention-25",
            "entity_uuid": "c155665b-a654-40f9-ad7d-a2aaf03e6231",
            "type": "Document_Contains_Entity",
        },
        {
            "doc_obj_id": "DocumentRelation-12",
            "document_uuid": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
            "entity_obj_id": "EntityMention-32",
            "entity_uuid": "38da5ce2-f827-4475-93e4-979517c57d2f",
            "type": "Document_Contains_Entity",
        },
        {
            "doc_obj_id": "DocumentRelation-13",
            "document_uuid": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
            "entity_obj_id": "EntityMention-33",
            "entity_uuid": "c8469c6c-9139-457c-a862-8b1742102f84",
            "type": "Document_Contains_Entity",
        },
        {
            "doc_obj_id": "DocumentRelation-14",
            "document_uuid": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
            "entity_obj_id": "EntityMention-36",
            "entity_uuid": "967a3381-14ae-4124-8f70-756fdbcec53f",
            "type": "Document_Contains_Entity",
        },
        {
            "doc_obj_id": "DocumentRelation-15",
            "document_uuid": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
            "entity_obj_id": "EntityMention-37",
            "entity_uuid": "c3cc0e47-6390-4663-a88d-a396e7259958",
            "type": "Document_Contains_Entity",
        },
        {
            "doc_obj_id": "DocumentRelation-16",
            "document_uuid": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
            "entity_obj_id": "EntityMention-38",
            "entity_uuid": "8f2f984a-85cc-4ce5-92df-4d5d8cf2aab6",
            "type": "Document_Contains_Entity",
        },
        {
            "doc_obj_id": "DocumentRelation-17",
            "document_uuid": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
            "entity_obj_id": "EntityMention-41",
            "entity_uuid": "2ed9d9c4-20e9-4368-a615-6a34fe70a095",
            "type": "Document_Contains_Entity",
        },
        {
            "doc_obj_id": "DocumentRelation-18",
            "document_uuid": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
            "entity_obj_id": "EntityMention-42",
            "entity_uuid": "87832124-24bb-4655-9465-6dba28f35f70",
            "type": "Document_Contains_Entity",
        },
        {
            "doc_obj_id": "DocumentRelation-19",
            "document_uuid": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
            "entity_obj_id": "EntityMention-50",
            "entity_uuid": "d8e96c44-dc3f-433d-abb2-b87ff9ca5ab3",
            "type": "Document_Contains_Entity",
        },
        {
            "doc_obj_id": "DocumentRelation-20",
            "document_uuid": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
            "entity_obj_id": "EntityMention-52",
            "entity_uuid": "78790ae7-3334-4349-a868-f196f687fb42",
            "type": "Document_Contains_Entity",
        },
        {
            "doc_obj_id": "DocumentRelation-21",
            "document_uuid": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
            "entity_obj_id": "EntityMention-53",
            "entity_uuid": "068d51fd-830b-4e32-9bdc-5446367b29ed",
            "type": "Document_Contains_Entity",
        },
        {
            "doc_obj_id": "DocumentRelation-22",
            "document_uuid": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
            "entity_obj_id": "EntityMention-55",
            "entity_uuid": "53677e74-3c98-4b02-a13b-b5cda310f693",
            "type": "Document_Contains_Entity",
        },
        {
            "doc_obj_id": "DocumentRelation-23",
            "document_uuid": "a480a4df-99db-46dd-b1c9-4253e3e2a5be",
            "entity_obj_id": "EntityMention-56",
            "entity_uuid": "1d2f20d6-efa3-48de-a18d-4d6c84149780",
            "type": "Document_Contains_Entity",
        },
    ],
}
