ARG BASE_IMAGE=redhat/ubi8
FROM ${BASE_IMAGE}

RUN dnf install -y git
RUN dnf install -y python3.12 python3.12-pip
RUN rm -f /usr/local/bin/pip /usr/local/bin/pip3 || true
RUN alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 100
RUN alternatives --install /usr/bin/pip pip /usr/bin/pip3.12 100
RUN alternatives --set python3 /usr/bin/python3.12
RUN alternatives --set pip /usr/bin/pip3.12
RUN ln -sf /usr/bin/python3 /usr/bin/python
RUN dnf clean all
RUN update-ca-trust
